---
title: "Fig 6c"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F, message=F)
library(readxl)
library(seqinr)
library(tidyverse)
library(reshape2)
library(forcats)
library(RColorBrewer)
library(kableExtra)
library(gridExtra)
```

# Read in the filtered peptide list from the main dataset and the reference sequences
```{r}
cdr3 <- data.frame(read_tsv("./antibodies_cdr3_variable_full.tsv"))
cdr3$cdr3_start <- str_locate(cdr3$amino_acid_sequence_Vregion, cdr3$amino_acid_sequence_cdr3)[,1]
cdr3$cdr3_end <- str_locate(cdr3$amino_acid_sequence_Vregion, cdr3$amino_acid_sequence_cdr3)[,2]

MQ_peptides <- read_tsv("../../main_dataset/mq_ab_filtered.tsv")
MSF_peptides <- read_tsv("../../main_dataset/msf_ab_filtered.tsv")
Casanovo_peptides <- read_tsv("../../main_dataset/casanovo_ab_filtered.tsv")

MQ_peptides$Tool <- "MaxQuant"
MSF_peptides$Tool <- "MSFragger"
Casanovo_peptides$Tool <- "Casanovo"

# Merge all tools together, exclude intensity / search engine score
All_peptides <- rbind(MQ_peptides[,-5], MSF_peptides[,-5], Casanovo_peptides[,-5])

All_peptides$enzyme <- str_replace_all(All_peptides$enzyme, "aspn", "AspN")
All_peptides$enzyme <- str_replace_all(All_peptides$enzyme, "ct", "Ct")
All_peptides$enzyme <- str_replace_all(All_peptides$enzyme, "tryp", "Tryp")
All_peptides$enzyme <- str_replace_all(All_peptides$enzyme, "ct+tryp", "Ct+Tryp")

All_peptides$Tool <- as_factor(All_peptides$Tool)
levels(All_peptides$Tool) <-  c("MaxQuant", "MSFragger", "Casanovo")

Tool_cols <- c("MaxQuant" = "#00858a", "MSFragger" = "#e46e00", "Casanovo" = "#6a3e37")

All_peptides$match_ig_type <- str_replace_all(All_peptides$match_ig_type, "Bri", "Brimab")
All_peptides$match_ig_type <- str_replace_all(All_peptides$match_ig_type, "Ust", "Umab")

# exclude peptides labelled contamination
All_peptides <- All_peptides %>% filter(is_contamination == FALSE)
```
# Import function to calculate miscleavage and coverage

```{r}
source("../utils.R")

# Calculate miscleavage for all exp peptides
All_peptides <- All_peptides %>% mutate(n_miscleavages = ifelse(enzyme == "Tryp", unlist(lapply(Sequence, function(x) calculate_miscleavages_trypsin(x))), ifelse(enzyme == "Ct", unlist(lapply(Sequence, function(x) calculate_miscleavages_chymotrypsin(x))), ifelse(enzyme == "AspN", unlist(lapply(Sequence, function(x) calculate_miscleavages_aspn(x))), ifelse(enzyme == "Ct+Tryp", unlist(lapply(Sequence, function(x) calculate_miscleavages_chymotrypsin(x))) + unlist(lapply(Sequence, function(x) calculate_miscleavages_trypsin(x))), 0)))))

# Remove peptides with > 2 miscleavage (predictions made by Casanovo)
All_peptides <- All_peptides %>% filter(n_miscleavages <= 2)

# Summarize the df to keep only unique peptides per Ab (remove dup peptides from different samples)
Sum_peptides <- All_peptides %>% group_by(match_ig_type, Sequence, Tool, n_miscleavages) %>% summarize()

# Keep only Casanovo peptides
Sum_peptides <- Sum_peptides %>% filter(Tool == "Casanovo")
```

# Function to plot coverage
```{r}
make_coverage_plot <- function(ab_name, df) {
  peptides <- df$Sequence # peptides that perfectly march to an ab
  # Locate the position of the peptide sequence and the cdr3 in the V region
  res_seq <- str_locate(cdr3[cdr3$sequence_name == ab_name, ]$amino_acid_sequence_Vregion, as.character(peptides)) # position number of peptide on V region
  res_cdr3 <- str_locate(cdr3[cdr3$sequence_name == ab_name, ]$amino_acid_sequence_Vregion, as.character(cdr3[cdr3$sequence_name == ab_name, ]$amino_acid_sequence_cdr3)) # position number of the cdr3
  
  df_cdr3 <- data.frame(Sequence = peptides,
                        start = res_seq[, 1],
                        end = res_seq[, 2], 
                        Tool = as.factor(df$Tool),
                        n_miscleavages = as.factor(df$n_miscleavages))
  # Order the peptides based on starting position in the V region
  df_cdr3 <- df_cdr3[with(df_cdr3, order(start, -end)), ]
  df_cdr3$y <- 1:nrow(df_cdr3)

  df_cdr3_tmp <- melt(df_cdr3, c("Sequence", "y", "n_miscleavages", "Tool"))
  # Plot the coverage
  p_coverage <- ggplot(df_cdr3_tmp, aes(x=value, y=y)) +
    geom_rect(aes(xmin = res_cdr3[1, 1],
                  xmax = res_cdr3[1, 2],
                  ymin = -Inf, ymax = Inf), fill = "#FDFD96", alpha = 0.05) + #cdr3
    geom_point(size = 0.2) +
    geom_segment(aes(x = start, y = y, xend = end, yend = y, color = Tool, linetype = n_miscleavages), size = 1, data = df_cdr3) +
    scale_color_manual(values = "#6a3e37") +
    scale_linetype_manual(values = c("0" = 1, "1" = 2, "2" = 3)) +
    #scale_x_continuous(breaks = c(seq(min(res_seq), max(res_seq), by = 20))) +
    guides(fill = guide_legend(keywidth = 1, keyheight = 1),
    linetype = guide_legend(keywidth = 3, keyheight = 1),
    colour = guide_legend(keywidth = 3, keyheight = 1)) +
    theme_classic() +
    theme(text = element_text(size = 20), legend.position = "none") +
    labs(x = "Position in the variable region", y = "", color = "Tool", linetype = "Miscleavages")
   
  ggsave(filename = paste0("./figures/",ab_name,".pdf"), plot = p_coverage, height = 6, width = 8, dpi = 600)
  p_coverage
}
```

# Panel C: show coverage plot of only Casanovo peptides, with CDR3 coverage and CDR3 coverage on top

```{r fig.height=6, fig.width=8}
make_coverage_plot("PGDM1400_HC", Sum_peptides[Sum_peptides$match_ig_type == "PGDM1400_HC", ])
make_coverage_plot("PGT121_HC", Sum_peptides[Sum_peptides$match_ig_type == "PGT121_HC", ])
```

```{r}
# Calculate CDRH3 and VDJ coverage
coverage_PGDM1400 <- tibble(coverage = get_coverage_percent(Sum_peptides$Sequence, "PGDM1400_HC", cdr3, "both"),
                            type = str_to_upper(names(coverage)))
coverage_PGT121 <- tibble(coverage = get_coverage_percent(Sum_peptides$Sequence, "PGT121_HC", cdr3, "both"),
                          type = str_to_upper(names(coverage)))
```

```{r fig.height=1.5, fig.width=8}
ggplot(data = coverage_PGDM1400, aes(x = coverage, y = type)) +
  geom_col(fill = "#6a3e37") +
  scale_x_continuous(limits = c(0,100)) +
  geom_text(aes(label = round(coverage,2), hjust = -0.2)) +
  theme_classic() +
  theme(text = element_text(size = 16)) +
  labs(x = "Sequence coverage (%)", y = "")

ggsave("./figures/coverage_PGDM1400_HC.pdf", height = 1.5, width = 8, dpi = 600)
```
```{r fig.height=1.5, fig.width=8}
ggplot(data = coverage_PGT121, aes(x = coverage, y = type)) +
  geom_col(fill = "#6a3e37") +
  scale_x_continuous(limits = c(0,100)) +
  geom_text(aes(label = round(coverage,2), hjust = -0.2)) +
  theme_classic() +
  theme(text = element_text(size = 16)) +
  labs(x = "Sequence coverage (%)", y = "")

ggsave("./figures/coverage_PGT121_HC.pdf", height = 1.5, width = 8, dpi = 600)
```
