---
title: "Fig 4e,f: coverage in single mAb vs multiple mAb samples"
output: pdf_document
---

```{r setup, include=FALSE, message=F}
source(here::here("setup.R"))
source(here::here("src", "get_coverage.R"))
source(here::here("src", "plotting", "plot_coverage_single_vs_multiple_spikeins.R"))
```

```{r}
df <- read_tsv(here::here("data", "processed", "peptides_preprocessed_TP.tsv"), show_col_types = FALSE)
mabs_seq <- read_tsv(here::here("metadata", "mabs_cdr3_variable_full.tsv"), show_col_types = FALSE)
sample_info <- read_tsv(here::here("metadata", "detailed_sample_description.tsv"))
```

```{r}
stats <- get_coverage_per_concentration_per_run(df, mabs_seq, sample_info) %>%
  filter(Sample %in% c(36:47, 55:58) & 
           match_ig_type %in% c("h9C12-WT_HC", "h9C12_LC", "Umab_HC", "Umab_LC", "PGDM1400_HC", "PGDM1400_LC")) %>%
  mutate(number_of_spike_ins = ifelse(n_abs == 1, "single", "multiple"))
```

```{r, fig.height=5, fig.width=9}
plot_coverage_single_vs_multiple_spikeins(stats[stats$match_ig_type %in% HC_names, ])
```

# Supplementary

```{r, fig.height=5, fig.width=9}
plot_coverage_single_vs_multiple_spikeins(stats[stats$match_ig_type %in% LC_names, ])
```



