---
title: "Casanovo score cutoof"
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
source("../../Khang_config.R")
```

# 1. Read Casanovo output files and merge in one file 

```{r, message=FALSE}

# path <- file.path(data_path, "casanovo_raw")
# 
# read_casanovo_output <- function(fname) {
#   df_tmp <- data.frame(read_tsv(fname, skip = 58)) # 57?
#   df_tmp <- df_tmp[, c("sequence", "search_engine_score.1.")]
#   colnames(df_tmp) <- c("Sequence",  "search_engine_score")
#   df_tmp$sample <- str_remove(basename(fname), ".mztab")
#   df_tmp
# }
# 
# df_res <- data.frame()
# 
# for (run in 1:4) {
#   for (enzyme in c("ct", "tryp", "aspn", "ct+tryp")) {
#     print(run)
#     print(enzyme)
#     casanovo_files <- list.files(file.path(path, paste0("run", run, "_", enzyme)),
#                                  full.names = T, pattern = ".mztab")
#     df <- lapply(casanovo_files, read_casanovo_output)
#     df <- do.call("rbind", df)
#     df$run <- paste0("run", run)
#     df$enzyme <- enzyme
#     df_res <- rbind(df, df_res)
#   }
# }
# 
# 
# 
# write_tsv(df_res, file.path(data_path, "casanovo_raw/casanovo_merged.tsv"))
```

# 2. Remove PTMs, merge identical pepides, filter peptides shorter than 5 AA and casanovo_engine_score smaller than 0.8

```{r}
df <- read_tsv("./casanovo_merged.tsv")
print(nrow(df))

df <- df[!is.na(df$search_engine_score), ]
print(nrow(df))

# Remove PTMs, e.g. YLTSM+15.995ASR will be replaced with YLTSMASR
df$Sequence <- str_replace_all(string = df$Sequence, pattern = "[0-9.+-]", replacement = "")

# Filter peptides shorter than 6 AA
df <- df[sapply(df$Sequence, nchar) > 6, ]
print(nrow(df))

# Create a new variable that indicates whether the x value is 0.8 or above
df <- df %>% mutate(fill = ifelse(search_engine_score >= 0.8, "above_0.8", "below_0.8"))  
```

# Histogram of search engine score distribution
```{r fig.height=4, fig.width=7}
ggplot(data = df, aes(x = search_engine_score)) +
  geom_histogram(aes(fill = fill), color = "black", binwidth = 0.1, boundary = -1.0) +
  scale_x_continuous(breaks = seq(-1.0, 1.0, by = 0.2)) +
  scale_fill_manual(values = c("above_0.8" = "#6a3e37", "below_0.8" = "white")) +
  geom_vline(xintercept = 0.8, linetype = 2) +
  theme_classic(base_size = 16) +
  theme(legend.position = "none") +
  labs(x = "Casanovo prediction score", y = "Peptide count")

#ggsave("./Casanovo_score_dist.pdf", height = 4, width = 7, dpi = 600)
```

# Filter peptides with engine score of different threshold: 0.5, 0.6, 0.7, 0.8, 0.9
```{r}
# Filter peptides which casanovo_engine_score smaller than 0.5
df_0.5 <- df[df$search_engine_score > 0.5, ]
print(nrow(df_0.5))
df_0.6 <- df[df$search_engine_score > 0.6, ]
print(nrow(df_0.6))
df_0.7 <- df[df$search_engine_score > 0.7, ]
print(nrow(df_0.7))
df_0.8 <- df[df$search_engine_score > 0.8, ]
print(nrow(df_0.8))
df_0.9 <- df[df$search_engine_score > 0.9, ]
print(nrow(df_0.9))


# Merge identical peptides within every filename (EHxxxx), enzyme, and run. Keep the highest search_engine_score for merged peptides
df_0.5 <- df_0.5 %>%
    dplyr::group_by(Sequence, sample, run, enzyme) %>% # for each unique peptide in a filename, run, and enzyme
    dplyr::arrange(-search_engine_score) %>% # sort by highest search_engine score
    dplyr::slice(1) # take the peptide with the highest search_engine score

colnames(df_0.5) <- c("Sequence", "search_engine_score", "Rawfilenumber", "run", "Protease")

df_0.6 <- df_0.6 %>%
    dplyr::group_by(Sequence, sample, run, enzyme) %>% # for each unique peptide in a filename, run, and enzyme
    dplyr::arrange(-search_engine_score) %>% # sort by highest search_engine score
    dplyr::slice(1) # take the peptide with the highest search_engine score

colnames(df_0.6) <- c("Sequence", "search_engine_score", "Rawfilenumber", "run", "Protease")

df_0.7 <- df_0.7 %>%
    dplyr::group_by(Sequence, sample, run, enzyme) %>% # for each unique peptide in a filename, run, and enzyme
    dplyr::arrange(-search_engine_score) %>% # sort by highest search_engine score
    dplyr::slice(1) # take the peptide with the highest search_engine score

colnames(df_0.7) <- c("Sequence", "search_engine_score", "Rawfilenumber", "run", "Protease")

df_0.8 <- df_0.8 %>%
    dplyr::group_by(Sequence, sample, run, enzyme) %>% # for each unique peptide in a filename, run, and enzyme
    dplyr::arrange(-search_engine_score) %>% # sort by highest search_engine score
    dplyr::slice(1) # take the peptide with the highest search_engine score

colnames(df_0.8) <- c("Sequence", "search_engine_score", "Rawfilenumber", "run", "Protease")

df_0.9 <- df_0.9 %>%
    dplyr::group_by(Sequence, sample, run, enzyme) %>% # for each unique peptide in a filename, run, and enzyme
    dplyr::arrange(-search_engine_score) %>% # sort by highest search_engine score
    dplyr::slice(1) # take the peptide with the highest search_engine score

colnames(df_0.9) <- c("Sequence", "search_engine_score", "Rawfilenumber", "run", "Protease")

threshold_count <- tibble(n_peptides = c(print(nrow(df_0.5)), print(nrow(df_0.6)), print(nrow(df_0.7)),
                                         print(nrow(df_0.8)), print(nrow(df_0.9))))

df_list <- list(df_0.5, df_0.6, df_0.7, df_0.8, df_0.9)
# peptides that match to the variable region but also overlap with constant
cdr3 <- data.frame(read_tsv(file.path(metadata_path, "antibodies_cdr3_variable_full.tsv")))

df_list <- lapply(df_list, function(x) data.frame(x))
df_list <- lapply(df_list, function(x) align_to_ab_sequences(x, cdr3))

threshold_count$n_ab_peptides <- sapply(df_list, function(x) nrow(x))
threshold_count$score_threshold <- c("0.5", "0.6", "0.7", "0.8", "0.9")
```

# Scatterplot of search engine score vs number of ab peptides per threshold
```{r fig.height=4, fig.width=7}
ggplot(data = threshold_count, aes(y = n_ab_peptides, x = n_peptides)) +
  geom_line(color = "#6a3e37") +
  geom_point(aes(color = score_threshold), size = 3) +
  geom_vline(xintercept = 1038994, linetype = 2) +
  geom_text(aes(label = n_ab_peptides), vjust = -0.3) +
  scale_color_brewer(type = "seq", palette = 6, direction = 1) +
  theme_bw(base_size = 16) +
  theme(legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt")) +
  labs(x = "Number of peptides", y = "Number of antibody peptides", color = "Threshold")

#ggsave("./Casanovo_score_cutoff.pdf", height = 4, width = 7, dpi = 600)
```

```{r}
df <- add_metainfo(df)
df <- is_cdr3_related(df, cdr3, cdr3_min_overlap=3)

df <- rename_enzymes(df) 

#write_tsv(df, file.path(data_path, "casanovo_ab_annotated.tsv"))
```




