---
title: "Igor test run BSA"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{float}
  - \floatplacement{figure}{H}
output: 
  bookdown::pdf_document2:
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F, message=F, fig.width = 8, fig.height = 5)
```

```{r libs, echo=FALSE, warning=F, message=F}
library(readr)
library(readxl)
library(seqinr)
library(ggplot2)
library(themeakbar)
theme_set(themeakbar())
#library(sjmisc)
library(reshape2)
library(forcats)
library(RColorBrewer)
#library(knitr)
library(forcats)
library(dplyr)
#library(stringr)
#library(kableExtra)
```

```{r, echo=FALSE, message=F, warning=F}
path <- "/Users/mariiac/bioinf/MSMS/igor_BSA/data/BSA/"

peptides_files <- list.files(path = path, pattern = "\\.txt", full.names = T)

df <- data.frame()
for (i in 1:length(peptides_files)) {
  pfile <- peptides_files[i]
  df_tmp <- read_tsv(pfile)
  df_tmp$sample_type <- unlist(strsplit(basename(pfile), "_|\\."))[3]
  if (i > 1) {
    colnames(df_tmp) <- colnames(df)
  }
  df <- rbind(df, df_tmp)
}

df <- df[, c("Sequence", "sample_type", "Proteins", "Leading razor protein", 
             colnames(df)[grepl("Intensity ", colnames(df), fixed = TRUE)])]


df <- melt(df, id=c("Sequence", "sample_type", "Proteins", "Leading razor protein"))
colnames(df) <- c("Sequence", "sample_type", "Proteins", "Leading razor protein", "concentration", "intensity")
df <- df[df$intensity > 0, ] 

df$concentration <- sapply(df$concentration, function(s) unlist(strsplit(as.character(s), " "))[2])

df$run_parameter <- df$sample_type
df$sample_type <- paste(df$sample_type, df$concentration, sep="_")

df$sample <- sapply(df$concentration, function(s) unlist(strsplit(as.character(s), "_"))[2])
df$concentration <- sapply(df$concentration, function(s) unlist(strsplit(as.character(s), "_"))[1])

df$concentration[df$concentration == "5pmol"] <- "5000fmol"

df <- df[df$`Leading razor protein`=="P02769", ]
```

# BSA

## Number of detected peptides

```{r tbl1, echo=F, warning=F, error=F, message=F}

df_stats <- df %>%
  group_by(run_parameter, concentration, sample) %>%
  summarise(n_peptides=n())

knitr::kable(df_stats,
  "latex", caption = "Number of BSA detected peptides in each sample. In 5fmol more peptides were detected in 100s-sensitive method. All methods have approximately equal number of detected BSA peptides in 5000 -- 50 fmol concentrations.")

```


```{r}

sample_names <- sort(unique(df$sample_type))

res_ratio <- data.frame()

for (i in 1:length(sample_names)) {
  for (j in 1:length(sample_names)) {
    if (i < j) {
      s1 <- sample_names[i]
      s2 <- sample_names[j]

      overlap <- merge(x = df[df$sample_type==s1, ], y = df[df$sample_type==s2, ], by = "Sequence")
      if (!is.null(overlap))
      {
        res <- data.frame(Sequence = overlap$Sequence,
                   #match_ig_type = overlap$match_ig_type.x,
                   #n_protein_matches = overlap$n_matches.x,
                   sample_type1 = rep(as.character(s1), nrow(overlap)),
                   intensity1 = overlap$intensity.x,
                   concentration1 = overlap$concentration.x, 
                   run_parameter1 = overlap$run_parameter.x,
                   sample1 = overlap$sample.x,
                   sample_type2 = rep(as.character(s2), nrow(overlap)),
                   intensity2 = overlap$intensity.y,
                   concentration2 = overlap$concentration.y,
                   run_parameter2 = overlap$run_parameter.y,
                   sample2 = overlap$sample.y,
                   intensity_ratio = overlap$intensity.x/overlap$intensity.y)
        res_ratio <- rbind(res_ratio, res)
      }
    }
  }
}

res_ratio$concentration1 <- sapply(res_ratio$concentration1, function(s) as.integer(unlist(strsplit(as.character(s), "fmol"))))
res_ratio$concentration2 <- sapply(res_ratio$concentration2, function(s) as.integer(unlist(strsplit(as.character(s), "fmol"))))
res_ratio$conc_ratio <- res_ratio$concentration1/res_ratio$concentration2

# compare between identical sample run parameters
res_ratio <- res_ratio[res_ratio$run_parameter1 == res_ratio$run_parameter2, ]

idx <- res_ratio$conc_ratio < 1
res_ratio$conc_ratio[idx] <- 1/res_ratio$conc_ratio[idx]
res_ratio$intensity_ratio[idx] <- 1/res_ratio$intensity_ratio[idx]

```

\newpage

## Intensity ratio

```{r, fig.cap="Intensity ratio between BSA peptides detected with each method. 100-s sensitive method has the least accurate intencity ratios."}

ggplot(res_ratio, aes(x=factor(conc_ratio), y=log10(intensity_ratio))) +
  geom_boxplot(position = position_dodge2(preserve = 'single')) +
  geom_jitter(position = position_dodge(0.8)) +
  #geom_point() +
  facet_grid(~run_parameter1, scales='free') +
  scale_y_continuous(breaks=-5:5, labels = 10^(-5:5)) +
  #theme(legend.key.size = unit(1, "cm")) +
  #geom_hline(data=hor_line, aes(yintercept = z), size=2) +
  labs(x="Concentration ratio",
      y = "log10(Intensity ratio)") +
  geom_hline(yintercept=0, linetype="dashed", color = "red") +
  geom_hline(yintercept=1, linetype="dashed", color = "red") +
  geom_hline(yintercept=2, linetype="dashed", color = "red") +
  geom_hline(yintercept=3, linetype="dashed", color = "red") +
  scale_fill_brewer(palette="Pastel2") +
  guides(fill = guide_legend(nrow = 1, title="Enzyme"))
```

```{r, fig.cap="(Supplementary) Intensity ratio between BSA peptides detected with each method within one sample."}
res_ratio <- res_ratio[res_ratio$sample1 == res_ratio$sample2, ]

ggplot(res_ratio, aes(x=factor(conc_ratio), y=log10(intensity_ratio), fill=sample1)) +
  geom_boxplot(position = position_dodge2(preserve = 'single')) +
  geom_jitter(position = position_dodge(0.8)) +
  #geom_point() +
  facet_grid(~run_parameter1, scales='free') +
  scale_y_continuous(breaks=-1:5, labels = 10^(-1:5)) +
  theme(legend.key.size = unit(.5, "cm")) +
  geom_hline(yintercept=1, linetype="dashed", color = "red") +
  geom_hline(yintercept=2, linetype="dashed", color = "red") +
  geom_hline(yintercept=3, linetype="dashed", color = "red") +
  #geom_hline(data=hor_line, aes(yintercept = z), size=2) +
  labs(x="Concentration ratio",
      y = "log10(Intensity ratio)") +
  scale_fill_brewer(palette="Pastel2") +
  guides(fill = guide_legend(nrow = 1, title="Sample"))
```


# BSA + HeLa

```{r}
path <- "/Users/mariiac/bioinf/MSMS/igor_BSA/data/BSA_HeLa/"

peptides_files <- list.files(path = path, pattern = "\\.txt", full.names = T)

df <- data.frame()
for (i in 1:length(peptides_files)) {
  pfile <- peptides_files[i]
  df_tmp <- read_tsv(pfile)
  df_tmp$sample_type <- unlist(strsplit(basename(pfile), "_|\\."))[5]
  if (i > 1) {
    colnames(df_tmp) <- colnames(df)
  }
  df <- rbind(df, df_tmp)
}

df <- df[, c("Sequence", "sample_type", "Proteins", "Leading razor protein",
             colnames(df)[grepl("Intensity ", colnames(df), fixed = TRUE)])]


df <- melt(df, id=c("Sequence", "sample_type", "Proteins", "Leading razor protein"))
colnames(df) <- c("Sequence", "sample_type", "Proteins", "Leading razor protein", "concentration", "intensity")
df <- df[df$intensity > 0, ]

df$sample <- sapply(df$concentration, function(s) unlist(strsplit(as.character(s), " "))[3])
df$sample <- sapply(df$sample, function(s) unlist(strsplit(as.character(s), "_"))[2])

df$concentration <- sapply(df$concentration, function(s) unlist(strsplit(as.character(s), " "))[2])

df$run_parameter <- df$sample_type
df$sample_type <- paste(df$sample_type, df$concentration, df$sample, sep="_")

df$concentration[df$concentration == "5pmol"] <- "5000fmol"

df <- df[df$`Leading razor protein`=="P02769", ]

```


## Number of detected peptides

```{r tbl2, echo=F, warning=F, error=F, message=F}

df_stats <- df %>%
  group_by(run_parameter, concentration, sample) %>%
  summarise(n_peptides=n())

knitr::kable(df_stats,
  "latex", caption = "Number of BSA peptides detected in each sample.")

```

\newpage

## Intensity ratio

```{r}

sample_names <- sort(unique(df$sample_type))

res_ratio <- data.frame()

for (i in 1:length(sample_names)) {
  for (j in 1:length(sample_names)) {
    if (i < j) {
      s1 <- sample_names[i]
      s2 <- sample_names[j]

      overlap <- merge(x = df[df$sample_type==s1, ], y = df[df$sample_type==s2, ], by = "Sequence")
      if (!is.null(overlap))
      {
        res <- data.frame(Sequence = overlap$Sequence,
                   #match_ig_type = overlap$match_ig_type.x,
                   #n_protein_matches = overlap$n_matches.x,
                   sample_type1 = rep(as.character(s1), nrow(overlap)),
                   intensity1 = overlap$intensity.x,
                   concentration1 = overlap$concentration.x,
                   run_parameter1 = overlap$run_parameter.x,
                   sample1 = overlap$sample.x,
                   sample_type2 = rep(as.character(s2), nrow(overlap)),
                   intensity2 = overlap$intensity.y,
                   concentration2 = overlap$concentration.y,
                   run_parameter2 = overlap$run_parameter.y,
                   sample2 = overlap$sample.y,
                   intensity_ratio = overlap$intensity.x/overlap$intensity.y)
        res_ratio <- rbind(res_ratio, res)
      }
    }
  }
}

res_ratio$concentration1 <- sapply(res_ratio$concentration1, function(s) as.integer(unlist(strsplit(as.character(s), "fmol"))))
res_ratio$concentration2 <- sapply(res_ratio$concentration2, function(s) as.integer(unlist(strsplit(as.character(s), "fmol"))))
res_ratio$conc_ratio <- res_ratio$concentration1/res_ratio$concentration2

# compare between identical sample run parameters
res_ratio <- res_ratio[res_ratio$run_parameter1 == res_ratio$run_parameter2, ]

idx <- res_ratio$conc_ratio < 1
res_ratio$conc_ratio[idx] <- 1/res_ratio$conc_ratio[idx]
res_ratio$intensity_ratio[idx] <- 1/res_ratio$intensity_ratio[idx]

```

```{r, fig.cap="Intensity ratio between BSA peptides detected with each method. Intensity ratio in BSA+HeLa experiments are less biased than in BSA only experiments."}

ggplot(res_ratio, aes(x=factor(conc_ratio), y=log10(intensity_ratio))) +
  geom_boxplot(position = position_dodge2(preserve = 'single')) +
  geom_jitter(position = position_dodge(0.8)) +
  #geom_point() +
  facet_grid(~run_parameter1, scales='free') +
  scale_y_continuous(breaks=-5:5, labels = 10^(-5:5)) +
  #theme(legend.key.size = unit(1, "cm")) +
  #geom_hline(data=hor_line, aes(yintercept = z), size=2) +
  labs(x="Concentration ratio",
      y = "log10(Intensity ratio)") +
  geom_hline(yintercept=0, linetype="dashed", color = "red") +
  geom_hline(yintercept=1, linetype="dashed", color = "red") +
  geom_hline(yintercept=2, linetype="dashed", color = "red") +
  geom_hline(yintercept=3, linetype="dashed", color = "red") +
  scale_fill_brewer(palette="Pastel2") +
  guides(fill = guide_legend(nrow = 1, title="Enzyme"))
```

```{r, fig.cap="(Supplementary) Intensity ratio between BSA peptides detected with each method within one sample."}
res_ratio <- res_ratio[res_ratio$sample1 == res_ratio$sample2, ]

ggplot(res_ratio, aes(x=factor(conc_ratio), y=log10(intensity_ratio), fill=sample1)) +
  geom_boxplot(position = position_dodge2(preserve = 'single')) +
  geom_jitter(position = position_dodge(0.8)) +
  #geom_point() +
  facet_grid(~run_parameter1, scales='free') +
  scale_y_continuous(breaks=-1:5, labels = 10^(-1:5)) +
  theme(legend.key.size = unit(.5, "cm")) +
  geom_hline(yintercept=1, linetype="dashed", color = "red") +
  geom_hline(yintercept=2, linetype="dashed", color = "red") +
  geom_hline(yintercept=3, linetype="dashed", color = "red") +
  #geom_hline(data=hor_line, aes(yintercept = z), size=2) +
  labs(x="Concentration ratio",
      y = "log10(Intensity ratio)") +
  scale_fill_brewer(palette="Pastel2") +
  guides(fill = guide_legend(nrow = 1, title="Sample"))
```

