---
title: "Fig 5"
output: pdf_document
---

```{r setup, include=FALSE}
#source("/storage/mariiac/msms_figures/my_config.R")
source("../my_config.R")
```

```{r}
df <- read_tsv(file.path(data_path, "all_peptides_preprocessed.tsv"))
df <- df[df$is_not_contamination, ]
```

```{r}
df <- df[df$match_ig_type!="h9C12_LC" & df$match_ig_type!="h9C12-WT_HC" & 
           df$match_ig_type!="h9C12-Q97A_HC" & df$tool!="Casanovo",]
 
df$concentration <- NA
df$concentration[df$match_ig_type == "Brimab_HC" |  df$match_ig_type == "Brimab_LC"] <- df$concentration_Brimab[df$match_ig_type == "Brimab_HC" |  df$match_ig_type == "Brimab_LC"]
df$concentration[df$match_ig_type == "Umab_HC" |  df$match_ig_type == "Umab_LC"] <- df$concentration_Umab[df$match_ig_type == "Umab_HC" |  df$match_ig_type == "Umab_LC"]
df$concentration[df$match_ig_type == "PGT121_HC" |  df$match_ig_type == "PGT121_LC"] <- df$concentration_PGT121[df$match_ig_type == "PGT121_HC" |  df$match_ig_type == "PGT121_LC"]
df$concentration[df$match_ig_type == "PGDM1400_HC" |  df$match_ig_type == "PGDM1400_LC"] <- df$concentration_PGDM1400[df$match_ig_type == "PGDM1400_HC" |  df$match_ig_type == "PGDM1400_LC"]
 
df <- df[df$concentration > 0,]
df$ab <- unlist(strsplit(as.character(df$match_ig_type), "_"))[c(T, F)]

#df$sample_type <- paste0(df$Sample, "_", df$Protease, "_", df$run)

res_ratio <- df %>%
  left_join(df, by = c("Sequence", "Protease", "tool", "match_ig_type"), relationship = "many-to-many") %>% 
  subset(Rawfilenumber.x != Rawfilenumber.y) %>%
  summarise(Sequence = Sequence, 
            Protease = Protease, 
            tool = tool, 
            match_ig_type = match_ig_type, 
            intensity1 = intensity.x, 
            intensity2 = intensity.y, 
            concentration1 = concentration.x,
            concentration2 = concentration.y,
            conc_ratio = concentration.x/concentration.y,
            ab = ab.x,
            run1 = run.x, 
            run2 = run.y, 
            is_cdr3_related = is_cdr3_related.x, 
            intensity_ratio = intensity.x/intensity.y)

idx <- res_ratio$conc_ratio < 1
res_ratio$conc_ratio[idx] <- 1/res_ratio$conc_ratio[idx]
res_ratio$intensity_ratio[idx] <- 1/res_ratio$intensity_ratio[idx]
```

```{r}
StripAttr <- function(x, attr_names = NULL) 
{
    if (is.null(attr_names)) 
        attributes(x) <- NULL
    else for (a in attr_names) attr(x, which = a) <- NULL
    return(x)
}

MedianCI <- function (x, conf.level = 0.95, sides = c("two.sided", "left", 
    "right"), na.rm = FALSE, method = c("exact", "boot"), R = 999) 
{
    if (na.rm) 
        x <- na.omit(x)
    MedianCI_Binom <- function(x, conf.level = 0.95, sides = c("two.sided", 
        "left", "right"), na.rm = FALSE) {
        if (na.rm) 
            x <- na.omit(x)
        n <- length(x)
        switch(match.arg(sides), two.sided = {
            k <- qbinom(p = (1 - conf.level)/2, size = n, prob = 0.5, 
                lower.tail = TRUE)
            ci <- sort(x)[c(k, n - k + 1)]
            attr(ci, "conf.level") <- 1 - 2 * pbinom(k - 1, size = n, 
                prob = 0.5)
        }, left = {
            k <- qbinom(p = (1 - conf.level), size = n, prob = 0.5, 
                lower.tail = TRUE)
            ci <- c(sort(x)[k], Inf)
            attr(ci, "conf.level") <- 1 - pbinom(k - 1, size = n, 
                prob = 0.5)
        }, right = {
            k <- qbinom(p = conf.level, size = n, prob = 0.5, 
                lower.tail = TRUE)
            ci <- c(-Inf, sort(x)[k])
            attr(ci, "conf.level") <- pbinom(k, size = n, prob = 0.5)
        })
        if (identical(StripAttr(ci), NA_real_)) {
            ci <- c(-Inf, Inf)
            attr(ci, "conf.level") <- 1
        }
        return(ci)
    }
    sides <- match.arg(sides, choices = c("two.sided", "left", 
        "right"), several.ok = FALSE)
    method <- match.arg(arg = method, choices = c("exact", "boot"))
    switch(method, exact = {
        r <- MedianCI_Binom(x, conf.level = conf.level, sides = sides)
    }, boot = {
        if (sides != "two.sided") conf.level <- 1 - 2 * (1 - 
            conf.level)
        boot.med <- boot(x, function(x, d) median(x[d], na.rm = na.rm), 
            R = R)
        r <- boot.ci(boot.med, conf = conf.level, type = "basic")[[4]][4:5]
    })
    med <- median(x, na.rm = na.rm)
    if (is.na(med)) {
        res <- rep(NA, 3)
    }
    else {
        res <- c(median = med, r)
        if (method == "exact") 
            attr(res, "conf.level") <- attr(r, "conf.level")
    }
    names(res) <- c("median", "lwr.ci", "upr.ci")
    if (sides == "left") 
        res[3] <- Inf
    else if (sides == "right") 
        res[2] <- -Inf
    return(res)
}
```

```{r}
make_intensity_ratio_plot <- function(res_ratio) {
  ci <- res_ratio %>%
  group_by(match_ig_type, Protease, tool, conc_ratio) %>%
  summarize(lwr.ci = MedianCI(intensity_ratio)[2], med = MedianCI(intensity_ratio)[1], upr.ci = MedianCI(intensity_ratio)[3])

ci <- ci[str_detect(ci$match_ig_type, "HC"), ]

pd <- position_dodge(0.5)
g <- ggplot(ci, aes(x=log10(conc_ratio), y=med, colour=tool)) + 
    geom_errorbar(aes(ymin=lwr.ci, ymax=upr.ci), width=.1, position=pd) +
    geom_line(position=pd) +
    geom_point(position=pd) +
    facet_grid(match_ig_type~Protease, scales='free_y') +
    geom_hline(yintercept=1, linetype="dotted", color = "#909090") +
    geom_hline(yintercept=10, linetype="dotted", color = "#909090") +
    geom_hline(yintercept=100, linetype="dotted", color = "#909090") +
    geom_hline(yintercept=1000, linetype="dotted", color = "#909090") +
    geom_text(aes(x=log10(conc_ratio), y=lwr.ci, label = round(lwr.ci,1), color = tool), size= 3, vjust = 1, position = position_dodge(width = .5)) +
  geom_text(aes(x=log10(conc_ratio), y=upr.ci, label = round(upr.ci,1), color = tool), size= 3, vjust = 0, position = position_dodge(width = .5)) +
    #scale_y_continuous(breaks=-2:4) +
    scale_x_discrete(labels = c("1:1", "1:10", "1:100", "1:1000"), drop = FALSE) +
  scale_y_continuous(trans='log10') +
    labs(x="Concentration ratio") +
    scale_colour_manual(values=c("#00858a", "#e46e00")) +
    theme_bw()
    
  plot(g)
  
  png(file.path(plot_path, paste0(c(chain_type, mode, ".png"), collapse = "_")), 
      width = 5, height = 4, units = 'in', res = 600)
  plot(g)
  dev.off()
}
```


```{r, fig.width=10, fig.height=6}



# ggplot(res_ratio, aes(x=factor(conc_ratio), y=log10(intensity_ratio),  fill=tool) ) +
#   #geom_boxplot(position = position_dodge2(preserve = 'single'), outlier.shape=NA) +
#   #geom_half_point(position = position_jitterdodge(0.2), size=0.01) +
#   geom_half_violin() +
#   geom_half_point(size=0.001, alpha = 0.2) +
#   facet_grid(match_ig_type~Protease, scales='free') +
#   scale_y_continuous(breaks=-5:5, labels = 10^(-5:5)) +
#   scale_x_discrete(labels = c("1:1", "1:10", "1:100", "1:1000"), drop = FALSE) +
#   labs(x="Concentration ratio",
#       y = "log10(Intensity ratio)") +
#   geom_hline(yintercept=0, linetype="dashed", color = "red") +
#   geom_hline(yintercept=1, linetype="dashed", color = "red") +
#   geom_hline(yintercept=2, linetype="dashed", color = "red") +
#   geom_hline(yintercept=3, linetype="dashed", color = "red") +
#   scale_fill_brewer(palette="Pastel2") +
#   scale_color_brewer(palette="Pastel2") +
#   theme(text = element_text(size=20)) +
#   theme_bw() +
#   guides(fill = guide_legend(nrow = 1, title="Run")) +
#   theme(legend.key.size = unit(2, 'cm'))
```


```{r, fig.width=10, fig.height=10}
ggplot(res_ratio[res_ratio$is_cdr3_related, ], aes(x=factor(conc_ratio), y=log10(intensity_ratio),  fill=tool) ) +
  #geom_boxplot(position = position_dodge2(preserve = 'single'), outlier.shape=NA) +
  #geom_point(position = position_jitterdodge(0.2), size=0.01) +
  geom_violin() +
  facet_grid(match_ig_type~Protease, scales='free') +
  scale_y_continuous(breaks=-5:5, labels = 10^(-5:5)) +
  scale_x_discrete(labels = c("1:1", "1:10", "1:100", "1:1000"), drop = FALSE) +
  labs(x="Concentration ratio",
      y = "log10(Intensity ratio)") +
  geom_hline(yintercept=0, linetype="dashed", color = "red") +
  geom_hline(yintercept=1, linetype="dashed", color = "red") +
  geom_hline(yintercept=2, linetype="dashed", color = "red") +
  geom_hline(yintercept=3, linetype="dashed", color = "red") +
  scale_fill_brewer(palette="Pastel2") +
  scale_color_brewer(palette="Pastel2") +
  theme(text = element_text(size=20)) +
  guides(fill = guide_legend(nrow = 1, title="Run")) +
  theme(legend.key.size = unit(2, 'cm'))
```

```{r, fig.width=10, fig.height=10}
ggplot(res_ratio[res_ratio$is_cdr3_related & res_ratio$conc_ratio == 1, ], aes(x=factor(conc_ratio), y=log10(intensity_ratio),  fill=tool) ) +
  #geom_violin(position = position_dodge2(preserve = 'single'), outlier.shape=NA) +
  geom_violin() +
  #geom_point(position = position_jitterdodge(0.2), size=0.01) +
  facet_grid(match_ig_type~concentration1, scales='free') +
  scale_y_continuous(breaks=-5:5, labels = 10^(-5:5)) +
  scale_x_discrete(labels = c("1:1", "1:10", "1:100", "1:1000"), drop = FALSE) +
  labs(x="Concentration ratio",
      y = "log10(Intensity ratio)") +
  geom_hline(yintercept=0, linetype="dashed", color = "red") +
  geom_hline(yintercept=1, linetype="dashed", color = "red") +
  geom_hline(yintercept=2, linetype="dashed", color = "red") +
  geom_hline(yintercept=3, linetype="dashed", color = "red") +
  scale_fill_brewer(palette="Pastel2") +
  scale_color_brewer(palette="Pastel2") +
  theme(text = element_text(size=20)) +
  guides(fill = guide_legend(nrow = 1, title="Run")) +
  theme(legend.key.size = unit(2, 'cm'))
```


```{r}
df <- read_tsv(file.path(data_path, "all_peptides_preprocessed.tsv"))
df <- df[df$is_not_contamination, ]

df <- df[df$match_ig_type!="h9C12_LC" & df$match_ig_type!="h9C12-WT_HC" & 
           df$match_ig_type!="h9C12-Q97A_HC" & df$tool!="Casanovo",]

df <- df[df$Sample >= 36 & df$Sample <= 47, ]
 
df$concentration <- NA
df$concentration[df$match_ig_type == "Brimab_HC" |  df$match_ig_type == "Brimab_LC"] <- df$concentration_Brimab[df$match_ig_type == "Brimab_HC" |  df$match_ig_type == "Brimab_LC"]
df$concentration[df$match_ig_type == "Umab_HC" |  df$match_ig_type == "Umab_LC"] <- df$concentration_Umab[df$match_ig_type == "Umab_HC" |  df$match_ig_type == "Umab_LC"]
df$concentration[df$match_ig_type == "PGT121_HC" |  df$match_ig_type == "PGT121_LC"] <- df$concentration_PGT121[df$match_ig_type == "PGT121_HC" |  df$match_ig_type == "PGT121_LC"]
df$concentration[df$match_ig_type == "PGDM1400_HC" |  df$match_ig_type == "PGDM1400_LC"] <- df$concentration_PGDM1400[df$match_ig_type == "PGDM1400_HC" |  df$match_ig_type == "PGDM1400_LC"]
 
df <- df[df$concentration > 0,]
df$ab <- unlist(strsplit(as.character(df$match_ig_type), "_"))[c(T, F)]

#df$sample_type <- paste0(df$Sample, "_", df$Protease, "_", df$run)

res_ratio <- df %>%
  left_join(df, by = c("Sequence", "Protease", "tool", "match_ig_type"), relationship = "many-to-many") %>% 
  subset(Rawfilenumber.x != Rawfilenumber.y) %>%
  summarise(Sequence = Sequence, 
            Protease = Protease, 
            tool = tool, 
            match_ig_type = match_ig_type, 
            intensity1 = intensity.x, 
            intensity2 = intensity.y, 
            concentration1 = concentration.x,
            concentration2 = concentration.y,
            conc_ratio = concentration.x/concentration.y,
            ab = ab.x,
            run1 = run.x, 
            run2 = run.y, 
            is_cdr3_related = is_cdr3_related.x, 
            intensity_ratio = intensity.x/intensity.y)

idx <- res_ratio$conc_ratio < 1
res_ratio$conc_ratio[idx] <- 1/res_ratio$conc_ratio[idx]
res_ratio$intensity_ratio[idx] <- 1/res_ratio$intensity_ratio[idx]

```

```{r, fig.width=10, fig.height=10}
ggplot(res_ratio[res_ratio$is_cdr3_related, ], aes(x=factor(conc_ratio), y=log10(intensity_ratio),  fill=tool) ) +
  geom_boxplot(position = position_dodge2(preserve = 'single'), outlier.shape=NA) +
  geom_point(position = position_jitterdodge(0.2), size=0.01) +
  #geom_violin() +
  facet_grid(match_ig_type~Protease, scales='free') +
  scale_y_continuous(breaks=-5:5, labels = 10^(-5:5)) +
  scale_x_discrete(labels = c("1:1", "1:10", "1:100", "1:1000"), drop = FALSE) +
  labs(x="Concentration ratio",
      y = "log10(Intensity ratio)") +
  geom_hline(yintercept=0, linetype="dashed", color = "red") +
  geom_hline(yintercept=1, linetype="dashed", color = "red") +
  geom_hline(yintercept=2, linetype="dashed", color = "red") +
  geom_hline(yintercept=3, linetype="dashed", color = "red") +
  scale_fill_brewer(palette="Pastel2") +
  scale_color_brewer(palette="Pastel2") +
  theme(text = element_text(size=20)) +
  guides(fill = guide_legend(nrow = 1, title="Run")) +
  theme(legend.key.size = unit(2, 'cm'))
```

