---
title: "Fig 5"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
source("../Khang_config.R")
source("../utils.R")

df <- read_tsv(file.path(data_path, "all_peptides_preprocessed.tsv"))
df <- df[df$is_not_contamination, ]
```

```{r}
# Exclude h9C12 since because they always present in the same sample together and shared peptides will sum up the intensity and the amount. While peptides covering the Q97A position will not sum up.
df <- df[df$match_ig_type!="h9C12_LC" & df$match_ig_type!="h9C12-WT_HC" & 
           df$match_ig_type!="h9C12-Q97A_HC" & df$tool!="Casanovo",]

# Create a col for mAb input, but only based on the input amount of the ref hit of that peptide 
df$concentration <- NA
df$concentration[df$match_ig_type == "Brimab_HC" |  df$match_ig_type == "Brimab_LC"] <- df$concentration_Brimab[df$match_ig_type == "Brimab_HC" |  df$match_ig_type == "Brimab_LC"]
df$concentration[df$match_ig_type == "Umab_HC" |  df$match_ig_type == "Umab_LC"] <- df$concentration_Umab[df$match_ig_type == "Umab_HC" |  df$match_ig_type == "Umab_LC"]
df$concentration[df$match_ig_type == "PGT121_HC" |  df$match_ig_type == "PGT121_LC"] <- df$concentration_PGT121[df$match_ig_type == "PGT121_HC" |  df$match_ig_type == "PGT121_LC"]
df$concentration[df$match_ig_type == "PGDM1400_HC" |  df$match_ig_type == "PGDM1400_LC"] <- df$concentration_PGDM1400[df$match_ig_type == "PGDM1400_HC" |  df$match_ig_type == "PGDM1400_LC"]
 
df <- df[df$concentration > 0,]
df$ab <- unlist(strsplit(as.character(df$match_ig_type), "_"))[c(T, F)]

# Add information on blood/ non blood for each sample
blood_ann <- tibble(Sample = 1:70,
                blood = TRUE)
blood_ann$blood[c(36:64,66)] <- FALSE
df <- left_join(df, blood_ann, by = "Sample")

# Create a df that compare two peptides with the same sequence, protease, tool, and mAb, but different sample number in THE SAME experimental replicate
# Create 3 categories for pairs of samples: 1 for both samples with blood, 2 for both samples without blood, 3 for one sample with and the other without blood
res_ratio <- df %>%
  left_join(df, by = c("Sequence", "Protease", "tool", "match_ig_type"), relationship = "many-to-many") %>% 
  subset(Rawfilenumber.x != Rawfilenumber.y) %>% subset(run.x == run.y) %>% 
  summarise(Sequence = Sequence, 
            Protease = Protease, 
            tool = tool, 
            match_ig_type = match_ig_type,
            is_cdr3_related = is_cdr3_related.x,
            intensity1 = intensity.x, 
            intensity2 = intensity.y,
            intensity_ratio = intensity.x/intensity.y,
            concentration1 = concentration.x,
            concentration2 = concentration.y,
            conc_ratio = concentration.x/concentration.y,
            ab = ab.x,
            run1 = run.x, 
            run2 = run.y,
            blood1 = blood.x,
            blood2 = blood.y,
            blood_state = ifelse(blood1 == TRUE & blood2 == TRUE, "blood",
                          ifelse(blood1 == FALSE & blood2 == FALSE, "no blood", "mixed"))
            )

# Perform inversion in cases when sample x is lower input than sample y
idx <- res_ratio$conc_ratio < 1
res_ratio$conc_ratio[idx] <- 1/res_ratio$conc_ratio[idx]
res_ratio$intensity_ratio[idx] <- 1/res_ratio$intensity_ratio[idx]

res_ratio$conc_ratio <- factor(res_ratio$conc_ratio)
```

# Calculate the 95% CI and draw lineplots
```{r}
# Functions to calculate the confidenec interval of the medians
StripAttr <- function(x, attr_names = NULL) 
{
    if (is.null(attr_names)) 
        attributes(x) <- NULL
    else for (a in attr_names) attr(x, which = a) <- NULL
    return(x)
}

MedianCI <- function (x, conf.level = 0.95, sides = c("two.sided", "left", 
    "right"), na.rm = FALSE, method = c("exact", "boot"), R = 999) 
{
    if (na.rm) 
        x <- na.omit(x)
    MedianCI_Binom <- function(x, conf.level = 0.95, sides = c("two.sided", 
        "left", "right"), na.rm = FALSE) {
        if (na.rm) 
            x <- na.omit(x)
        n <- length(x)
        switch(match.arg(sides), two.sided = {
            k <- qbinom(p = (1 - conf.level)/2, size = n, prob = 0.5, 
                lower.tail = TRUE)
            ci <- sort(x)[c(k, n - k + 1)]
            attr(ci, "conf.level") <- 1 - 2 * pbinom(k - 1, size = n, 
                prob = 0.5)
        }, left = {
            k <- qbinom(p = (1 - conf.level), size = n, prob = 0.5, 
                lower.tail = TRUE)
            ci <- c(sort(x)[k], Inf)
            attr(ci, "conf.level") <- 1 - pbinom(k - 1, size = n, 
                prob = 0.5)
        }, right = {
            k <- qbinom(p = conf.level, size = n, prob = 0.5, 
                lower.tail = TRUE)
            ci <- c(-Inf, sort(x)[k])
            attr(ci, "conf.level") <- pbinom(k, size = n, prob = 0.5)
        })
        if (identical(StripAttr(ci), NA_real_)) {
            ci <- c(-Inf, Inf)
            attr(ci, "conf.level") <- 1
        }
        return(ci)
    }
    sides <- match.arg(sides, choices = c("two.sided", "left", 
        "right"), several.ok = FALSE)
    method <- match.arg(arg = method, choices = c("exact", "boot"))
    switch(method, exact = {
        r <- MedianCI_Binom(x, conf.level = conf.level, sides = sides)
    }, boot = {
        if (sides != "two.sided") conf.level <- 1 - 2 * (1 - 
            conf.level)
        boot.med <- boot(x, function(x, d) median(x[d], na.rm = na.rm), 
            R = R)
        r <- boot.ci(boot.med, conf = conf.level, type = "basic")[[4]][4:5]
    })
    med <- median(x, na.rm = na.rm)
    if (is.na(med)) {
        res <- rep(NA, 3)
    }
    else {
        res <- c(median = med, r)
        if (method == "exact") 
            attr(res, "conf.level") <- attr(r, "conf.level")
    }
    names(res) <- c("median", "lwr.ci", "upr.ci")
    if (sides == "left") 
        res[3] <- Inf
    else if (sides == "right") 
        res[2] <- -Inf
    return(res)
}
```

# SIR on the heavy chain
```{r}
res_ratio_hc <- res_ratio %>% filter(str_detect(match_ig_type, "_HC")) %>% filter(Protease != "AspN")

res_ratio_hc_med_blood <- res_ratio_hc %>% filter(blood_state == "blood") %>% group_by(match_ig_type, Protease, conc_ratio, blood_state, run1) %>% summarise(sir_med_vdj = median(intensity_ratio))
res_ratio_hc_med_noblood <- res_ratio_hc %>% filter(blood_state == "no blood") %>% group_by(match_ig_type, Protease, conc_ratio, blood_state, run1) %>% summarise(sir_med_vdj = median(intensity_ratio))
res_ratio_hc_med_mixed <- res_ratio_hc %>% filter(blood_state == "mixed") %>% group_by(match_ig_type, Protease, conc_ratio, blood_state, run1) %>% summarise(sir_med_vdj = median(intensity_ratio))

# Calculate the confidence interval for the median signal intensity on the heavy chain peptides
ci_hc <- res_ratio_hc %>%
  group_by(match_ig_type, Protease, conc_ratio, blood_state, run1) %>%
  summarize(lwr.ci = MedianCI(intensity_ratio)[2], med = MedianCI(intensity_ratio)[1], upr.ci = MedianCI(intensity_ratio)[3])

pd <- position_dodge(0.5)
```

# Only samples pair non-blood
```{r fig.height=7, fig.width=7}
ggplot(res_ratio_hc %>% filter(blood_state == 2), aes(x = factor(conc_ratio), y = intensity_ratio)) +
  geom_boxplot(aes(color = tool), width = 0.75, outlier.shape = NA) +
  #geom_point(pch = 1, size = 0.4, cex = 3) +
  scale_y_log10(breaks = 10^(-3:4), labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  geom_hline(yintercept=1, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=10, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=100, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=1000, linetype="dotted", color = "#909090") +
  scale_color_manual(values = Tool_cols) +
  geom_text(data = res_ratio_hc_med_mq %>% filter(blood_state == 2), aes(x = factor(conc_ratio), y = 0.0001, label = round(sir_med_vdj,2)), color = "#00858a", size = 3) +
  geom_text(data = res_ratio_hc_med_msf %>% filter(blood_state == 2), aes(x = factor(conc_ratio), y = 0.00001, label = round(sir_med_vdj,2)), color = "#e46e00", size = 3) +
  facet_grid(factor(match_ig_type, levels = HC_names) ~ Protease) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x = "mAb input ratio", y = "MS signal intensity ratio")
```

# Only sample pairs with blood
```{r fig.height=7, fig.width=7}
ggplot(res_ratio_hc %>% filter(blood_state == 1), aes(x = factor(conc_ratio), y = intensity_ratio)) +
  geom_boxplot(aes(color = tool), width = 0.75, outlier.shape = NA) +
  scale_y_log10(breaks = 10^(-3:4), labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  geom_hline(yintercept=1, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=10, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=100, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=1000, linetype="dotted", color = "#909090") +
  scale_color_manual(values = Tool_cols) +
  geom_text(data = res_ratio_hc_med_mq %>% filter(blood_state == 1), aes(x = factor(conc_ratio), y = 0.0001, label = round(sir_med_vdj,2)), color = "#00858a", size = 3) +
  geom_text(data = res_ratio_hc_med_msf %>% filter(blood_state == 1), aes(x = factor(conc_ratio), y = 0.00001, label = round(sir_med_vdj,2)), color = "#e46e00", size = 3) +
  facet_grid(factor(match_ig_type, levels = HC_names) ~ Protease) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x = "mAb input ratio", y = "MS signal intensity ratio")
```

# SIR of all samples by presence of blood in each sample pair: non-blood or blood
```{r fig.height=8, fig.width=12}
ggplot(res_ratio_hc %>% filter(blood_state == "blood"), aes(x = factor(conc_ratio), y = intensity_ratio)) +
  #geom_violin(aes(color = run1), width = 0.9, lwd = 0.3, outlier.shape = NA) +
  geom_point(aes(color = run1), shape = 21, size = 0.1, stroke = 0.05, position = position_jitterdodge()) +
  geom_boxplot(aes(color = run1), width = 0.5, lwd = 0.3, outlier.shape = NA) +
  scale_y_log10(breaks = 10^(-3:4), labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  geom_hline(yintercept=1, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=10, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=100, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=1000, linetype="dotted", color = "#909090") +
  scale_color_manual(values = c("#48cae4", "#0096c7", "#0077B6", "#03045E")) +
  geom_text(data = res_ratio_hc_med_blood, aes(x = factor(conc_ratio), y = 0.0001, label = round(sir_med_vdj,1), color = run1), size = 2) +
  facet_grid(factor(match_ig_type, levels = HC_names) ~ factor(Protease, levels = c("Tryp", "Ct", "Ct+Tryp")) + run1) +
  theme_classic() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90), 
        strip.text.x = element_blank(), strip.text.y = element_blank()
        ) +
  labs(x = "mAb input ratio", y = "MS signal intensity ratio")

#ggsave("./figures/sir_blood.png", height = 8, width = 12, dpi = 600)
```

```{r fig.height=8, fig.width=12}
ggplot(res_ratio_hc %>% filter(blood_state == "no blood"), aes(x = factor(conc_ratio), y = intensity_ratio)) +
  #geom_violin(aes(color = run1), width = 0.9, lwd = 0.3, outlier.shape = NA) +
  geom_point(aes(color = run1), shape = 21, size = 0.1, stroke = 0.05, position = position_jitterdodge()) +
  geom_boxplot(aes(color = run1), width = 0.5, lwd = 0.3, outlier.shape = NA) +
  scale_y_log10(breaks = 10^(-3:4), labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  geom_hline(yintercept=1, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=10, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=100, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=1000, linetype="dotted", color = "#909090") +
  scale_color_manual(values = c("#48cae4", "#0096c7", "#0077B6", "#03045E")) +
  geom_text(data = res_ratio_hc_med_noblood, aes(x = factor(conc_ratio), y = 0.0001, label = round(sir_med_vdj,1), color = run1), size = 2) +
  facet_grid(factor(match_ig_type, levels = HC_names) ~ factor(Protease, levels = c("Tryp", "Ct", "Ct+Tryp")) + run1) +
  theme_classic() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90), 
        strip.text.x = element_blank(), strip.text.y = element_blank()
        ) +
  labs(x = "mAb input ratio", y = "MS signal intensity ratio")

#ggsave("./figures/sir_noblood.png", height = 8, width = 12, dpi = 600)
```

# Unused

```{r fig.height=10, fig.width=10}
ggplot(res_ratio_hc, aes(x = factor(conc_ratio), y = intensity_ratio)) +
  geom_hline(yintercept=1, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=10, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=100, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=1000, linetype="dotted", color = "#909090") +
  # Plot for signal intensity ratio distribution
  geom_violin(aes(color = blood_state), width = 1, lwd = 0.2, outlier.shape = NA) +
  geom_point(aes(color = blood_state), shape = 21, size = 0.05, stroke = 0.05, alpha = 0.3, position = position_jitterdodge(jitter.width = 0.6, jitter.height = 0)) +
  geom_boxplot(aes(color = blood_state), width = 0.3, lwd = 0.2, outlier.shape = NA) +
  geom_text(data = res_ratio_hc_med_blood, aes(x = factor(conc_ratio), y = 0.00002, label = round(sir_med_vdj,1)), color = "#DE4328", size = 2) +
 geom_text(data = res_ratio_hc_med_mixed, aes(x = factor(conc_ratio), y = 0.00002, label = round(sir_med_vdj,1)), color = "#DE9E28", size = 2) +
  geom_text(data = res_ratio_hc_med_noblood, aes(x = factor(conc_ratio), y = 0.00002, label = round(sir_med_vdj,1)), color = "#000000", size = 2) +
  # Plot for median CI of the signal intensity ratio
  #geom_errorbar(data = ci_hc, aes(x = conc_ratio, y = med, ymin = lwr.ci, ymax = upr.ci, color = blood_state), width = 0.1, position = pd) +
  #geom_line(data = ci_hc, aes(x = as.numeric(conc_ratio), y = med, color = blood_state), position = pd) +
  #geom_point(data = ci_hc, aes(x = conc_ratio, y = med, color = blood_state), size = 0.2, position = pd) +
  #geom_text(data = ci_hc, aes(x = conc_ratio, y = lwr.ci, label = round(lwr.ci,1), color = blood_state), size = 2, vjust = 1.5, position = pd) +
  #geom_text(data = ci_hc, aes(x = conc_ratio, y = upr.ci, label = round(upr.ci,1), color = blood_state), size = 2, vjust = -0.5, position = pd) +
  # Scale and coloring
  scale_x_discrete(labels = c("1:1", "10:1", "100:1", "1000:1"), drop = FALSE) +
  scale_y_log10(breaks = c(1, 10, 100, 1000), labels = c("1:1", "10:1", "100:1", "1000:1")) +
  #scale_y_log10(breaks = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000), labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  scale_color_manual(values = c("#DE4328", "#DE9E28","#000000")) +
  facet_grid(factor(match_ig_type, levels = HC_names) ~ factor(Protease, levels = c("Ct+Tryp", "Tryp", "Ct", "AspN")) + blood_state) +
  theme_classic() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, hjust = 0.95), 
        strip.text.x = element_blank(), strip.text.y = element_blank()
        ) +
  labs(x = "mAb input ratio", y = "MS signal intensity ratio", color = "Presence of blood IgG in sample pair")

#ggsave("./figures/sir_blood_nolabel.png", height = 10, width = 10, dpi = 600)
```

```{r fig.height=10, fig.width=14}
ggplot(data = ci_hc %>% filter(blood_state == "no blood"), aes(x = conc_ratio, y = med, colour = run1)) + 
  geom_errorbar(aes(ymin = lwr.ci, ymax = upr.ci), width = 0.1, position = pd) +
  geom_line(aes(x = as.numeric(conc_ratio), y = med), position = pd) +
  geom_point(position = pd) +
  facet_grid(factor(match_ig_type, levels = HC_names) ~ Protease + run1) +
  geom_hline(yintercept = 1, linetype = "dotted", color = "#909090") +
  geom_hline(yintercept = 10, linetype = "dotted", color = "#909090") +
  geom_hline(yintercept = 100, linetype = "dotted", color = "#909090") +
  geom_hline(yintercept = 1000, linetype = "dotted", color = "#909090") +
  geom_text(aes(x = conc_ratio, y = lwr.ci, label = round(lwr.ci,1), color = run1), size = 2, vjust = 1.5, position = pd) +
  geom_text(aes(x = conc_ratio, y = upr.ci, label = round(upr.ci,1), color = run1), size = 2, vjust = -0.5, position = pd) +
  #scale_y_continuous(breaks=-2:4) +
  scale_x_discrete(labels = c("1:1", "10:1", "100:1", "1000:1"), drop = FALSE) +
  scale_y_log10(breaks = 10^(-3:4), labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  labs(x = "mAb input ratio", y = "MS signal intensity ratio") +
  #scale_color_manual(values = c("#DE4328", "#DE9E28","#000000")) +
  theme_classic() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, hjust = 0.95),
        #strip.text.y = element_blank()
        )
```
```{r fig.height=10, fig.width=14}
ggplot(data = ci_hc %>% filter(blood_state == "blood"), aes(x = conc_ratio, y = med, colour = run1)) + 
  geom_errorbar(aes(ymin = lwr.ci, ymax = upr.ci), width = 0.1, position = pd) +
  geom_line(aes(x = as.numeric(conc_ratio), y = med), position = pd) +
  geom_point(position = pd) +
  facet_grid(factor(match_ig_type, levels = HC_names) ~ Protease + run1) +
  geom_hline(yintercept = 1, linetype = "dotted", color = "#909090") +
  geom_hline(yintercept = 10, linetype = "dotted", color = "#909090") +
  geom_hline(yintercept = 100, linetype = "dotted", color = "#909090") +
  geom_hline(yintercept = 1000, linetype = "dotted", color = "#909090") +
  geom_text(aes(x = conc_ratio, y = lwr.ci, label = round(lwr.ci,1), color = run1), size = 2, vjust = 1.5, position = pd) +
  geom_text(aes(x = conc_ratio, y = upr.ci, label = round(upr.ci,1), color = run1), size = 2, vjust = -0.5, position = pd) +
  #scale_y_continuous(breaks=-2:4) +
  scale_x_discrete(labels = c("1:1", "10:1", "100:1", "1000:1"), drop = FALSE) +
  scale_y_log10(breaks = 10^(-3:4), labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  labs(x = "mAb input ratio", y = "MS signal intensity ratio") +
  #scale_color_manual(values = c("#DE4328", "#DE9E28","#000000")) +
  theme_classic() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, hjust = 0.95), 
        #strip.text.y = element_blank()
        )
```

```{r fig.height=8, fig.width=10}
ggplot(data = ci_hc, aes(x = conc_ratio, y = med, colour = run1)) + 
  geom_errorbar(aes(ymin = lwr.ci, ymax = upr.ci), width = 0.1, position = pd) +
  geom_line(aes(x = as.numeric(conc_ratio), y = med), position = pd) +
  geom_point(position = pd) +
  facet_grid(factor(match_ig_type, levels = HC_names) ~ Protease + run1) +
  geom_hline(yintercept = 1, linetype = "dotted", color = "#909090") +
  geom_hline(yintercept = 10, linetype = "dotted", color = "#909090") +
  geom_hline(yintercept = 100, linetype = "dotted", color = "#909090") +
  geom_hline(yintercept = 1000, linetype = "dotted", color = "#909090") +
  #geom_text(aes(x = conc_ratio, y = lwr.ci, label = round(lwr.ci,1), color = run1), size = 2, vjust = 1.5, position = pd) +
  #geom_text(aes(x = conc_ratio, y = upr.ci, label = round(upr.ci,1), color = run1), size = 2, vjust = -0.5, position = pd) +
  #scale_y_continuous(breaks=-2:4) +
  scale_x_discrete(labels = c("1:1", "10:1", "100:1", "1000:1"), drop = FALSE) +
  scale_y_log10(breaks = 10^(-3:4), labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  labs(x = "mAb input ratio", y = "MS signal intensity ratio") +
  #scale_color_manual(values = c("#DE4328", "#DE9E28","#000000")) +
  theme_classic() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, hjust = 0.95), 
        #strip.text.y = element_blank()
        )
```