---
title: "Fig 5 v2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
source("../Khang_config.R")
source("../utils.R")

df <- read_tsv(file.path(data_path, "all_peptides_preprocessed.tsv"))
df <- df[df$is_not_contamination, ]
```

```{r}
# Exclude h9C12 since because they always present in the same sample together and shared peptides will sum up the intensity and the amount. While peptides covering the Q97A position will not sum up.
df <- df[df$match_ig_type!="h9C12_LC" & df$match_ig_type!="h9C12-WT_HC" & 
           df$match_ig_type!="h9C12-Q97A_HC" & df$tool!="Casanovo",]

# Create a col for mAb input, but only based on the input amount of the ref hit of that peptide 
df$concentration <- NA
df$concentration[df$match_ig_type == "Brimab_HC" |  df$match_ig_type == "Brimab_LC"] <- df$concentration_Brimab[df$match_ig_type == "Brimab_HC" |  df$match_ig_type == "Brimab_LC"]
df$concentration[df$match_ig_type == "Umab_HC" |  df$match_ig_type == "Umab_LC"] <- df$concentration_Umab[df$match_ig_type == "Umab_HC" |  df$match_ig_type == "Umab_LC"]
df$concentration[df$match_ig_type == "PGT121_HC" |  df$match_ig_type == "PGT121_LC"] <- df$concentration_PGT121[df$match_ig_type == "PGT121_HC" |  df$match_ig_type == "PGT121_LC"]
df$concentration[df$match_ig_type == "PGDM1400_HC" |  df$match_ig_type == "PGDM1400_LC"] <- df$concentration_PGDM1400[df$match_ig_type == "PGDM1400_HC" |  df$match_ig_type == "PGDM1400_LC"]
 
df <- df[df$concentration > 0,]
df$ab <- unlist(strsplit(as.character(df$match_ig_type), "_"))[c(T, F)]

# Add information on blood/ non blood for each sample
blood_ann <- tibble(Sample = 1:70,
                blood = TRUE)
blood_ann$blood[c(36:64,66)] <- FALSE
df <- left_join(df, blood_ann, by = "Sample")

# Create a df that compare two peptides with the same sequence, protease, tool, and mAb, but different sample number in THE SAME experimental replicate
# Create 3 categories for pairs of samples: 1 for both samples with blood, 2 for both samples without blood, 3 for one sample with and the other without blood
res_ratio <- df %>%
  left_join(df, by = c("Sequence", "Protease", "tool", "match_ig_type"), relationship = "many-to-many") %>% 
  subset(Rawfilenumber.x != Rawfilenumber.y) %>% subset(run.x == run.y) %>% 
  summarise(Sequence = Sequence, 
            Protease = Protease, 
            tool = tool, 
            match_ig_type = match_ig_type,
            is_cdr3_related = is_cdr3_related.x,
            intensity1 = intensity.x, 
            intensity2 = intensity.y,
            intensity_ratio = intensity.x/intensity.y,
            concentration1 = concentration.x,
            concentration2 = concentration.y,
            conc_ratio = concentration.x/concentration.y,
            ab = ab.x,
            run1 = run.x, 
            run2 = run.y,
            blood1 = blood.x,
            blood2 = blood.y,
            blood_state = ifelse(blood1 == TRUE & blood2 == TRUE, "blood",
                          ifelse(blood1 == FALSE & blood2 == FALSE, "no blood", "mixed"))
            )

# Perform inversion in cases when sample x is lower input than sample y
idx <- res_ratio$conc_ratio < 1
res_ratio$conc_ratio[idx] <- 1/res_ratio$conc_ratio[idx]
res_ratio$intensity_ratio[idx] <- 1/res_ratio$intensity_ratio[idx]

#res_ratio$conc_ratio <- factor(res_ratio$conc_ratio)
```


# SIR on the heavy chain and light chain
```{r}
# Remove AspN because too few peptides
res_ratio_hc <- res_ratio %>% filter(str_detect(match_ig_type, "_HC")) %>% filter(Protease != "AspN")
res_ratio_lc <- res_ratio %>% filter(str_detect(match_ig_type, "_LC")) %>% filter(Protease != "AspN")

#res_ratio_hc <- res_ratio %>% filter(str_detect(match_ig_type, "_HC"))

# Remove sample pairs where one is with and one is without blood
res_ratio_hc <- res_ratio_hc %>% filter(!blood_state == "mixed")
res_ratio_lc <- res_ratio_lc %>% filter(!blood_state == "mixed")


# Convert both intensity ratio and input ratio in log10 scale
res_ratio_hc$log_intensity_ratio <- log10(res_ratio_hc$intensity_ratio)
res_ratio_lc$log_intensity_ratio <- log10(res_ratio_lc$intensity_ratio)

res_ratio_hc$log_conc_ratio <- log10(res_ratio_hc$conc_ratio)
res_ratio_lc$log_conc_ratio <- log10(res_ratio_lc$conc_ratio)


# Calculate median of the log10 signal intensity ratio
res_ratio_hc_med_blood <- res_ratio_hc %>% filter(blood_state == "blood") %>% group_by(match_ig_type, Protease, log_conc_ratio, run1) %>% summarise(med = median(log_intensity_ratio), med2 = median(intensity_ratio), N = n())
res_ratio_lc_med_blood <- res_ratio_lc %>% filter(blood_state == "blood") %>% group_by(match_ig_type, Protease, log_conc_ratio, run1) %>% summarise(med = median(log_intensity_ratio), med2 = median(intensity_ratio), N = n())


res_ratio_hc_med_noblood <- res_ratio_hc %>% filter(blood_state == "no blood") %>% group_by(match_ig_type, Protease, log_conc_ratio, run1) %>% summarise(med = median(log_intensity_ratio), med2 = median(intensity_ratio), N = n())
res_ratio_lc_med_noblood <- res_ratio_lc %>% filter(blood_state == "no blood") %>% group_by(match_ig_type, Protease, log_conc_ratio, run1) %>% summarise(med = median(log_intensity_ratio), med2 = median(intensity_ratio), N = n())


# Make a linear regression model from the log sir, weighted by number of data points, extract the coefficients
coefs_blood <- res_ratio_hc_med_blood %>%
  group_by(Protease, run1, match_ig_type) %>%
  do(regr = lm(med ~ log_conc_ratio, weights = N, .)) %>%
  summarise(Protease = Protease, 
            run1 = run1, 
            match_ig_type = match_ig_type,
            intercept = coef(regr)[1], 
            slope = coef(regr)[2], 
            r2 = summary(regr)$r.squared)

coefs_blood_lc <- res_ratio_lc_med_blood %>%
  group_by(Protease, run1, match_ig_type) %>%
  do(regr = lm(med ~ log_conc_ratio, weights = N, .)) %>%
  summarise(Protease = Protease, 
            run1 = run1, 
            match_ig_type = match_ig_type,
            intercept = coef(regr)[1], 
            slope = coef(regr)[2], 
            r2 = summary(regr)$r.squared)

coefs_blood$eq <- paste0("italic(log(y)) == ", format(coefs_blood$intercept, digits = 2, scientific = TRUE), 
                   " + ", format(coefs_blood$slope, digits = 2, scientific = TRUE), " %.% italic(log(x))")
coefs_blood_lc$eq <- paste0("italic(log(y)) == ", format(coefs_blood_lc$intercept, digits = 2, scientific = TRUE), 
                   " + ", format(coefs_blood_lc$slope, digits = 2, scientific = TRUE), " %.% italic(log(x))")

coefs_blood$eq <- str_replace_all(coefs_blood$eq, "\\+ -", "\\- ")
coefs_blood_lc$eq <- str_replace_all(coefs_blood_lc$eq, "\\+ -", "\\- ")

coefs_blood$r2 <- paste0("italic(R)^2 == ", format(coefs_blood$r2, digits = 2))
coefs_blood_lc$r2 <- paste0("italic(R)^2 == ", format(coefs_blood_lc$r2, digits = 2))


coefs_noblood <- res_ratio_hc_med_noblood %>%
  group_by(Protease, run1, match_ig_type) %>%
  do(regr = lm(med ~ log_conc_ratio, weights = N, .)) %>%
  summarise(Protease = Protease, 
            run1 = run1, 
            match_ig_type = match_ig_type,
            intercept = coef(regr)[1], 
            slope = coef(regr)[2], 
            r2 = summary(regr)$r.squared)

coefs_noblood_lc <- res_ratio_lc_med_noblood %>%
  group_by(Protease, run1, match_ig_type) %>%
  do(regr = lm(med ~ log_conc_ratio, weights = N, .)) %>%
  summarise(Protease = Protease, 
            run1 = run1, 
            match_ig_type = match_ig_type,
            intercept = coef(regr)[1], 
            slope = coef(regr)[2], 
            r2 = summary(regr)$r.squared)

coefs_noblood$eq <- paste0("italic(log(y)) == ", format(coefs_noblood$intercept, digits = 2, scientific = TRUE), 
                   " + ", format(coefs_noblood$slope, digits = 2, scientific = TRUE), " %.% italic(log(x))")
coefs_noblood_lc$eq <- paste0("italic(log(y)) == ", format(coefs_noblood_lc$intercept, digits = 2, scientific = TRUE), 
                   " + ", format(coefs_noblood_lc$slope, digits = 2, scientific = TRUE), " %.% italic(log(x))")

coefs_noblood$eq <- str_replace_all(coefs_noblood$eq, "\\+ -", "\\- ")
coefs_noblood_lc$eq <- str_replace_all(coefs_noblood_lc$eq, "\\+ -", "\\- ")

coefs_noblood$r2 <- paste0("italic(R)^2 == ", format(coefs_noblood$r2, digits = 2))
coefs_noblood_lc$r2 <- paste0("italic(R)^2 == ", format(coefs_noblood_lc$r2, digits = 2))

# Manual remove regression with only one group
coefs_blood <- coefs_blood[-c(14,15),]
coefs_blood_lc <- coefs_blood_lc[-c(14),]
coefs_noblood <- coefs_noblood[-c(4,13,27),]

# Create the same coef df but for ground truth
coefs_blood_gt <- coefs_blood
coefs_blood_gt$intercept <- 0
coefs_blood_gt$slope <- 1

coefs_blood_lc_gt <- coefs_blood_lc
coefs_blood_lc_gt$intercept <- 0
coefs_blood_lc_gt$slope <- 1

coefs_noblood_gt <- coefs_noblood
coefs_noblood_gt$intercept <- 0
coefs_noblood_gt$slope <- 1

coefs_noblood_lc_gt <- coefs_noblood_lc
coefs_noblood_lc_gt$intercept <- 0
coefs_noblood_lc_gt$slope <- 1
```

# SIR of all samples by presence of blood in each sample pair: non-blood or blood
```{r fig.height=4, fig.width=12}
ggplot(res_ratio_hc %>% filter(blood_state == "blood") %>% filter(Protease != "AspN"), aes(x = log_conc_ratio, y = log_intensity_ratio, color = factor(log_conc_ratio))) +
  geom_point(aes(fill = run1), color = "black", shape = 21, size = 0.1, stroke = 0.03, position = position_jitterdodge()) +
  geom_boxplot(aes(fill = run1), width = 0.5, lwd = 0.3, outlier.shape = NA) +
  geom_abline(data = coefs_blood, aes(intercept = intercept, slope = slope), color = "#FF00F2", linewidth = 0.75, linetype = "dashed") +
  geom_abline(data = coefs_blood_gt, aes(intercept = intercept, slope = slope), color = "black", linewidth = 0.25) + # ground truth
  scale_color_manual(values = c("black", "black", "black", "black")) +
  scale_fill_manual(values = c("#969696", "#bdbdbd", "#d9d9d9", "#ffffff")) +
  geom_text(data = res_ratio_hc_med_blood, aes(x = log_conc_ratio, y = 4.2, label = round(med2,1)), color = "black", size = 2) +
  geom_text(data = coefs_blood, aes(-0.75, -4, label = eq), parse = TRUE, size = 1.5, color = "black", hjust = 0) +
  geom_text(data = coefs_blood, aes(-0.75, -4.5, label = r2), parse = TRUE, size = 1.5, color = "black", hjust = 0) +
  scale_x_continuous(breaks = 0:3, labels = c(1, 10, 100, 1000)) +
  scale_y_continuous(breaks = -3:4, labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  facet_grid(factor(match_ig_type, levels = HC_names) ~ factor(Protease, levels = c("Tryp", "Ct", "Ct+Tryp")) + run1) +
  theme_bw() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.45), axis.text.y = element_text(size = 7),
        strip.text.x = element_blank(), strip.text.y = element_blank(),
        panel.spacing = unit(0.1, "lines")
        ) +
  labs(x = "mAb input ratio", y = "MS signal intensity ratio")

ggsave("./figures/sir_blood.png", height = 4, width = 12, dpi = 600)
```

```{r fig.height=4, fig.width=12}
ggplot(res_ratio_lc %>% filter(blood_state == "blood") %>% filter(Protease != "AspN"), aes(x = log_conc_ratio, y = log_intensity_ratio, color = factor(log_conc_ratio))) +
  geom_point(aes(fill = run1), color = "black", shape = 21, size = 0.1, stroke = 0.03, position = position_jitterdodge()) +
  geom_boxplot(aes(fill = run1), width = 0.5, lwd = 0.3, outlier.shape = NA) +
  geom_abline(data = coefs_blood_lc, aes(intercept = intercept, slope = slope), color = "#FF00F2", linewidth = 0.75, linetype = "dashed") +
  geom_abline(data = coefs_blood_lc_gt, aes(intercept = intercept, slope = slope), color = "black", linewidth = 0.25) + # ground truth
  scale_color_manual(values = c("black", "black", "black", "black")) +
  scale_fill_manual(values = c("#969696", "#bdbdbd", "#d9d9d9", "#ffffff")) +
  geom_text(data = res_ratio_lc_med_blood, aes(x = log_conc_ratio, y = 4.2, label = round(med2,1)), color = "black", size = 2) +
  geom_text(data = coefs_blood_lc, aes(-0.75, -4, label = eq), parse = TRUE, size = 1.5, color = "black", hjust = 0) +
  geom_text(data = coefs_blood_lc, aes(-0.75, -4.5, label = r2), parse = TRUE, size = 1.5, color = "black", hjust = 0) +
  scale_x_continuous(breaks = 0:3, labels = c(1, 10, 100, 1000)) +
  scale_y_continuous(breaks = -3:4, labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  facet_grid(factor(match_ig_type, levels = LC_names) ~ factor(Protease, levels = c("Tryp", "Ct", "Ct+Tryp")) + run1) +
  theme_bw() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.45), axis.text.y = element_text(size = 7),
        strip.text.x = element_blank(), strip.text.y = element_blank(),
        panel.spacing = unit(0.1, "lines")
        ) +
  labs(x = "mAb input ratio", y = "MS signal intensity ratio")

#ggsave("./figures/sir_blood_lc.png", height = 4, width = 12, dpi = 600)
```

```{r fig.height=4, fig.width=12}
ggplot(res_ratio_hc %>% filter(blood_state == "no blood") %>% filter(Protease != "AspN"), aes(x = log_conc_ratio, y = log_intensity_ratio, color = factor(log_conc_ratio))) +
  geom_point(aes(fill = run1), color = "black", shape = 21, size = 0.1, stroke = 0.03, position = position_jitterdodge()) +
  geom_boxplot(aes(fill = run1), width = 0.5, lwd = 0.3, outlier.shape = NA) +
  geom_abline(data = coefs_noblood, aes(intercept = intercept, slope = slope), color = "#FF00F2", linewidth = 0.75, linetype = "dashed") +
  geom_abline(data = coefs_noblood_gt, aes(intercept = intercept, slope = slope), color = "black", linewidth = 0.25) + # ground truth
  #scale_color_manual(values = c("#48cae4", "#0096c7", "#0077B6", "#03045E")) +
  scale_color_manual(values = c("black", "black", "black", "black")) +
  scale_fill_manual(values = c("#969696", "#bdbdbd", "#d9d9d9", "#ffffff")) +
  geom_text(data = res_ratio_hc_med_noblood, aes(x = log_conc_ratio, y = 4.2, label = round(med2,1)), color = "black", size = 2) +
  geom_text(data = coefs_noblood, aes(-0.75, -4, label = eq), parse = TRUE, size = 1.5, color = "black", hjust = 0) +
  geom_text(data = coefs_noblood, aes(-0.75, -4.5, label = r2), parse = TRUE, size = 1.5, color = "black", hjust = 0) +
  scale_x_continuous(breaks = 0:3, labels = c(1, 10, 100, 1000)) +
  scale_y_continuous(breaks = -3:4, labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  facet_grid(factor(match_ig_type, levels = HC_names) ~ factor(Protease, levels = c("Tryp", "Ct", "Ct+Tryp")) + run1) +
  theme_bw() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.45), axis.text.y = element_text(size = 7),
        strip.text.x = element_blank(), strip.text.y = element_blank(),
        panel.spacing = unit(0.1, "lines")
        ) +
  labs(x = "mAb input ratio", y = "MS signal intensity ratio")

#ggsave("./figures/sir_noblood.png", height = 4, width = 12, dpi = 600)
```

```{r fig.height=5, fig.width=12}
ggplot(res_ratio_lc %>% filter(blood_state == "no blood") %>% filter(Protease != "AspN"), aes(x = log_conc_ratio, y = log_intensity_ratio, color = factor(log_conc_ratio))) +
  geom_point(aes(fill = run1), color = "black", shape = 21, size = 0.1, stroke = 0.03, position = position_jitterdodge()) +
  geom_boxplot(aes(fill = run1), width = 0.5, lwd = 0.3, outlier.shape = NA) +
  geom_abline(data = coefs_noblood_lc, aes(intercept = intercept, slope = slope), color = "#FF00F2", linewidth = 0.75, linetype = "dashed") +
  geom_abline(data = coefs_noblood_lc_gt, aes(intercept = intercept, slope = slope), color = "black", linewidth = 0.25) + # ground truth
  #scale_color_manual(values = c("#48cae4", "#0096c7", "#0077B6", "#03045E")) +
  scale_color_manual(values = c("black", "black", "black", "black")) +
  scale_fill_manual(values = c("#969696", "#bdbdbd", "#d9d9d9", "#ffffff")) +
  geom_text(data = res_ratio_lc_med_noblood, aes(x = log_conc_ratio, y = 4.2, label = round(med2,1)), color = "black", size = 2) +
  geom_text(data = coefs_noblood_lc, aes(-0.75, -4, label = eq), parse = TRUE, size = 1.5, color = "black", hjust = 0) +
  geom_text(data = coefs_noblood_lc, aes(-0.75, -4.5, label = r2), parse = TRUE, size = 1.5, color = "black", hjust = 0) +
  scale_x_continuous(breaks = 0:3, labels = c(1, 10, 100, 1000)) +
  scale_y_continuous(breaks = -3:4, labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  facet_grid(factor(match_ig_type, levels = LC_names) ~ factor(Protease, levels = c("Tryp", "Ct", "Ct+Tryp")) + run1) +
  theme_bw() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.45), axis.text.y = element_text(size = 7),
        strip.text.x = element_blank(), strip.text.y = element_blank(),
        panel.spacing = unit(0.1, "lines")
        ) +
  labs(x = "mAb input ratio", y = "MS signal intensity ratio")

#ggsave("./figures/sir_noblood_lc.png", height = 4, width = 12, dpi = 600)
```