---
title: "Coverage denovo complexity"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F, message=F)
library(readxl)
library(seqinr)
library(tidyverse)
library(reshape2)
library(forcats)
library(RColorBrewer)
library(kableExtra)
library(gridExtra)
source("../../utils.R")
source("../../Khang_config.R")
```

# Read in the filtered peptide list from the main dataset and the reference sequences
```{r include=FALSE}
cdr3 <- data.frame(read_tsv("./antibodies_cdr3_variable_full.tsv"))
cdr3$cdr3_start <- str_locate(cdr3$amino_acid_sequence_Vregion, cdr3$amino_acid_sequence_cdr3)[,1]
cdr3$cdr3_end <- str_locate(cdr3$amino_acid_sequence_Vregion, cdr3$amino_acid_sequence_cdr3)[,2]

MQ_peptides <- read_tsv("../../../main_dataset/mq_ab_filtered.tsv")
MSF_peptides <- read_tsv("../../../main_dataset/msf_ab_filtered.tsv")
Casanovo_peptides <- read_tsv("../../../main_dataset/casanovo_ab_filtered.tsv")

MQ_peptides$Tool <- "MaxQuant"
MSF_peptides$Tool <- "MSFragger"
Casanovo_peptides$Tool <- "Casanovo"

# Merge all tools together, exclude intensity / search engine score
All_peptides <- rbind(MQ_peptides[,-5], MSF_peptides[,-5], Casanovo_peptides[,-5])

All_peptides$enzyme <- str_replace_all(All_peptides$enzyme, "aspn", "AspN")
All_peptides$enzyme <- str_replace_all(All_peptides$enzyme, "ct", "Ct")
All_peptides$enzyme <- str_replace_all(All_peptides$enzyme, "tryp", "Tryp")
All_peptides$enzyme <- str_replace_all(All_peptides$enzyme, "ct+tryp", "Ct+Tryp")

All_peptides$Tool <- as_factor(All_peptides$Tool)
levels(All_peptides$Tool) <-  c("MaxQuant", "MSFragger", "Casanovo")

Tool_cols <- c("MaxQuant" = "#00858a", "MSFragger" = "#e46e00", "Casanovo" = "#6a3e37")

All_peptides$match_ig_type <- str_replace_all(All_peptides$match_ig_type, "Bri", "Brimab")
All_peptides$match_ig_type <- str_replace_all(All_peptides$match_ig_type, "Ust", "Umab")

# exclude peptides labelled contamination
All_peptides <- All_peptides %>% filter(is_contamination == FALSE)
```
# Import function to calculate miscleavage and coverage

```{r}
# Calculate miscleavage for all exp peptides
All_peptides <- All_peptides %>% mutate(n_miscleavages = ifelse(enzyme == "Tryp", unlist(lapply(Sequence, function(x) calculate_miscleavages_trypsin(x))), ifelse(enzyme == "Ct", unlist(lapply(Sequence, function(x) calculate_miscleavages_chymotrypsin(x))), ifelse(enzyme == "AspN", unlist(lapply(Sequence, function(x) calculate_miscleavages_aspn(x))), ifelse(enzyme == "Ct+Tryp", unlist(lapply(Sequence, function(x) calculate_miscleavages_chymotrypsin(x))) + unlist(lapply(Sequence, function(x) calculate_miscleavages_trypsin(x))), 0)))))

# Remove peptides with > 2 miscleavage (predictions made by Casanovo)
All_peptides <- All_peptides %>% filter(n_miscleavages <= 2)

# Keep only Casanovo peptides
All_peptides <- All_peptides %>% filter(Tool == "Casanovo")
```

# Before calculating coverage, from all peptides create subsets by selecting samples having mAbs at different concentrations
```{r}
# Heavy chain
h9C12_Q97A_HC_1 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(`concentration_h9C12-Q97A` == 1))$Sequence, "h9C12-Q97A_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "h9C12-Q97A_HC",
                          mab_input = 1)
h9C12_Q97A_HC_10 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(`concentration_h9C12-Q97A` == 10))$Sequence, "h9C12-Q97A_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "h9C12-Q97A_HC",
                          mab_input = 10)
h9C12_Q97A_HC_100 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(`concentration_h9C12-Q97A` == 100))$Sequence, "h9C12-Q97A_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "h9C12-Q97A_HC",
                          mab_input = 100)
h9C12_Q97A_HC_1000 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(`concentration_h9C12-Q97A` == 1000))$Sequence, "h9C12-Q97A_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "h9C12-Q97A_HC",
                          mab_input = 1000)

h9C12_WT_HC_1 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(`concentration_h9C12-WT` == 1))$Sequence, "h9C12-WT_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "h9C12-WT_HC",
                          mab_input = 1)
h9C12_WT_HC_10 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(`concentration_h9C12-WT` == 10))$Sequence, "h9C12-WT_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "h9C12-WT_HC",
                          mab_input = 10)
h9C12_WT_HC_100 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(`concentration_h9C12-WT` == 100))$Sequence, "h9C12-WT_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "h9C12-WT_HC",
                          mab_input = 100)
h9C12_WT_HC_1000 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(`concentration_h9C12-WT` == 1000))$Sequence, "h9C12-WT_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "h9C12-WT_HC",
                          mab_input = 1000)

Brimab_HC_1 <-  tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Bri == 1))$Sequence, "Brimab_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Brimab_HC",
                          mab_input = 1)
Brimab_HC_10 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Bri == 10))$Sequence, "Brimab_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Brimab_HC",
                          mab_input = 10)
Brimab_HC_100 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Bri == 100))$Sequence, "Brimab_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Brimab_HC",
                          mab_input = 100)
Brimab_HC_1000 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Bri == 1000))$Sequence, "Brimab_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Brimab_HC",
                          mab_input = 1000)

Umab_HC_1 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Ust == 1))$Sequence, "Umab_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Umab_HC",
                          mab_input = 1)
Umab_HC_10 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Ust == 10))$Sequence, "Umab_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Umab_HC",
                          mab_input = 10)
Umab_HC_100 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Ust == 100))$Sequence, "Umab_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Umab_HC",
                          mab_input = 100)
Umab_HC_1000 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Ust == 1000))$Sequence, "Umab_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Umab_HC",
                          mab_input = 1000)

PGT121_HC_1 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGT121 == 1))$Sequence, "PGT121_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGT121_HC",
                          mab_input = 1)
PGT121_HC_10 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGT121 == 10))$Sequence, "PGT121_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGT121_HC",
                          mab_input = 10)
PGT121_HC_100 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGT121 == 100))$Sequence, "PGT121_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGT121_HC",
                          mab_input = 100)
PGT121_HC_1000 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGT121 == 1000))$Sequence, "PGT121_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGT121_HC",
                          mab_input = 1000)

PGDM1400_HC_1 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGDM1400 == 1))$Sequence, "PGDM1400_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGDM1400_HC",
                          mab_input = 1)
PGDM1400_HC_10 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGDM1400 == 10))$Sequence, "PGDM1400_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGDM1400_HC",
                          mab_input = 10)
PGDM1400_HC_100 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGDM1400 == 100))$Sequence, "PGDM1400_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGDM1400_HC",
                          mab_input = 100)
PGDM1400_HC_1000 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGDM1400 == 1000))$Sequence, "PGDM1400_HC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGDM1400_HC",
                          mab_input = 1000)

coverage_hc_conc <- bind_rows(h9C12_Q97A_HC_1, h9C12_Q97A_HC_10, h9C12_Q97A_HC_100, h9C12_Q97A_HC_1000,
                              h9C12_WT_HC_1, h9C12_WT_HC_10, h9C12_WT_HC_100, h9C12_WT_HC_1000,
                              Brimab_HC_1, Brimab_HC_10, Brimab_HC_100, Brimab_HC_1000,
                              Umab_HC_1, Umab_HC_10, Umab_HC_100, Umab_HC_1000,
                              PGT121_HC_1, PGT121_HC_10, PGT121_HC_100, PGT121_HC_1000,
                              PGDM1400_HC_1, PGDM1400_HC_10, PGDM1400_HC_100, PGDM1400_HC_1000)
                              
```

```{r}
# Light chain
h9C12_LC_1 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(`concentration_h9C12-WT` == 1))$Sequence, "h9C12_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "h9C12_LC",
                          mab_input = 1)
h9C12_LC_10 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(`concentration_h9C12-WT` == 10))$Sequence, "h9C12_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "h9C12_LC",
                          mab_input = 10)
h9C12_LC_100 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(`concentration_h9C12-WT` == 100))$Sequence, "h9C12_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "h9C12_LC",
                          mab_input = 100)
h9C12_LC_1000 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(`concentration_h9C12-WT` == 1000))$Sequence, "h9C12_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "h9C12_LC",
                          mab_input = 1000)


Brimab_LC_1 <-  tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Bri == 1))$Sequence, "Brimab_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Brimab_LC",
                          mab_input = 1)
Brimab_LC_10 <-  tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Bri == 10))$Sequence, "Brimab_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Brimab_LC",
                          mab_input = 10)
Brimab_LC_100 <-  tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Bri == 100))$Sequence, "Brimab_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Brimab_LC",
                          mab_input = 100)
Brimab_LC_1000 <-  tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Bri == 1000))$Sequence, "Brimab_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Brimab_LC",
                          mab_input = 1000)


Umab_LC_1 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Ust == 1))$Sequence, "Umab_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Umab_LC",
                          mab_input = 1)
Umab_LC_10 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Ust == 10))$Sequence, "Umab_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Umab_LC",
                          mab_input = 10)
Umab_LC_100 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Ust == 100))$Sequence, "Umab_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Umab_LC",
                          mab_input = 100)
Umab_LC_1000 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_Ust == 1000))$Sequence, "Umab_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "Umab_LC",
                          mab_input = 1000)


PGT121_LC_1 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGT121 == 1))$Sequence, "PGT121_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGT121_LC",
                          mab_input = 1)
PGT121_LC_10 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGT121 == 10))$Sequence, "PGT121_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGT121_LC",
                          mab_input = 10)
PGT121_LC_100 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGT121 == 100))$Sequence, "PGT121_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGT121_LC",
                          mab_input = 100)
PGT121_LC_1000 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGT121 == 1000))$Sequence, "PGT121_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGT121_LC",
                          mab_input = 1000)


PGDM1400_LC_1 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGDM1400 == 1))$Sequence, "PGDM1400_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGDM1400_LC",
                          mab_input = 1)
PGDM1400_LC_10 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGDM1400 == 10))$Sequence, "PGDM1400_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGDM1400_LC",
                          mab_input = 10)
PGDM1400_LC_100 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGDM1400 == 100))$Sequence, "PGDM1400_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGDM1400_LC",
                          mab_input = 100)
PGDM1400_LC_1000 <- tibble(coverage = get_coverage_percent((All_peptides %>% filter(concentration_PGDM1400 == 1000))$Sequence, "PGDM1400_LC", annotation = cdr3, mode = "both"),
                          type = str_to_upper(names(coverage)),
                          mab_name = "PGDM1400_LC",
                          mab_input = 1000)

coverage_lc_conc <- bind_rows(h9C12_LC_1, h9C12_LC_10, h9C12_LC_100, h9C12_LC_1000,
                              Brimab_LC_1, Brimab_LC_10, Brimab_LC_100, Brimab_LC_1000,
                              Umab_LC_1, Umab_LC_10, Umab_LC_100, Umab_LC_1000,
                              PGT121_LC_1, PGT121_LC_10, PGT121_LC_100, PGT121_LC_1000,
                              PGDM1400_LC_1, PGDM1400_LC_10, PGDM1400_LC_100, PGDM1400_LC_1000)

coverage_lc_conc$type <- str_replace_all(coverage_lc_conc$type, "VDJ", "VJ")
```

```{r fig.height=5, fig.width=4}
ggplot(data = coverage_hc_conc, aes(x = factor(mab_input), y = coverage)) +
  geom_col(fill = "#6a3e37") +
  facet_grid(factor(mab_name, levels = HC_names)~factor(type, levels = c("VDJ", "CDR3"))) +
  scale_y_continuous(limits = c(0,120), breaks = c(0,25,50,75,100)) +
  geom_text(aes(label = round(coverage,2), vjust = -0.2), size = 3) +
  theme_classic() +
  theme(text = element_text(size = 12), strip.text.y = element_blank()) +
  labs(x = "mAb input (ng)", y = "Sequence coverage (%)")

#ggsave("./figures/coverage_Casanovo_HC_input.pdf", height = 5, width = 4, dpi = 600)
```

```{r fig.height=5, fig.width=4}
ggplot(data = coverage_lc_conc, aes(x = factor(mab_input), y = coverage)) +
  geom_col(fill = "#6a3e37") +
  facet_grid(factor(mab_name, levels = LC_names)~factor(type, levels = c("VJ", "CDR3"))) +
  scale_y_continuous(limits = c(0,120), breaks = c(0,25,50,75,100)) +
  geom_text(aes(label = round(coverage,2), vjust = -0.2), size = 3) +
  theme_classic() +
  theme(text = element_text(size = 12), strip.text.y = element_blank()) +
  labs(x = "mAb input (ng)", y = "Sequence coverage (%)")

#ggsave("./figures/coverage_Casanovo_LC_input.pdf", height = 5, width = 4, dpi = 600)
```

# Casanovo coverage in mono vs polyclonal samples
```{r}
All_peptides_mono <- All_peptides %>% filter(n_abs == 1)
All_peptides_poly <- All_peptides %>% filter(n_abs > 1)
```


```{r}
# Heavy chain
h9C12_Q97A_HC_mono <- tibble(coverage = get_coverage_percent(All_peptides_mono$Sequence, "h9C12-Q97A_HC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "h9C12-Q97A_HC", mab_number = "single")
h9C12_WT_HC_mono <- tibble(coverage = get_coverage_percent(All_peptides_mono$Sequence, "h9C12-WT_HC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "h9C12-WT_HC", mab_number = "single")
Brimab_HC_mono <- tibble(coverage = get_coverage_percent(All_peptides_mono$Sequence, "Brimab_HC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "Brimab_HC", mab_number = "single")
Umab_HC_mono <- tibble(coverage = get_coverage_percent(All_peptides_mono$Sequence, "Umab_HC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "Umab_HC", mab_number = "single")
PGT121_HC_mono <- tibble(coverage = get_coverage_percent(All_peptides_mono$Sequence, "PGT121_HC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "PGT121_HC", mab_number = "single")
PGDM1400_HC_mono <- tibble(coverage = get_coverage_percent(All_peptides_mono$Sequence, "PGDM1400_HC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "PGDM1400_HC", mab_number = "single")

h9C12_Q97A_HC_poly <- tibble(coverage = get_coverage_percent(All_peptides_poly$Sequence, "h9C12-Q97A_HC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "h9C12-Q97A_HC", mab_number = "multiple")
h9C12_WT_HC_poly <- tibble(coverage = get_coverage_percent(All_peptides_poly$Sequence, "h9C12-WT_HC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "h9C12-WT_HC", mab_number = "multiple")
Brimab_HC_poly <- tibble(coverage = get_coverage_percent(All_peptides_poly$Sequence, "Brimab_HC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "Brimab_HC", mab_number = "multiple")
Umab_HC_poly <- tibble(coverage = get_coverage_percent(All_peptides_poly$Sequence, "Umab_HC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "Umab_HC", mab_number = "multiple")
PGT121_HC_poly <- tibble(coverage = get_coverage_percent(All_peptides_poly$Sequence, "PGT121_HC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "PGT121_HC", mab_number = "multiple")
PGDM1400_HC_poly <- tibble(coverage = get_coverage_percent(All_peptides_poly$Sequence, "PGDM1400_HC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "PGDM1400_HC", mab_number = "multiple")

coverage_hc_mab_number <- bind_rows(h9C12_Q97A_HC_mono, h9C12_WT_HC_mono, Brimab_HC_mono, Umab_HC_mono, PGT121_HC_mono, PGDM1400_HC_mono, h9C12_Q97A_HC_poly, h9C12_WT_HC_poly, Brimab_HC_poly, Umab_HC_poly, PGT121_HC_poly, PGDM1400_HC_poly)

# Light chain
h9C12_LC_mono <- tibble(coverage = get_coverage_percent(All_peptides_mono$Sequence, "h9C12_LC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "h9C12_LC", mab_number = "single")
Brimab_LC_mono <- tibble(coverage = get_coverage_percent(All_peptides_mono$Sequence, "Brimab_LC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "Brimab_LC", mab_number = "single")
Umab_LC_mono <- tibble(coverage = get_coverage_percent(All_peptides_mono$Sequence, "Umab_LC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "Umab_LC", mab_number = "single")
PGT121_LC_mono <- tibble(coverage = get_coverage_percent(All_peptides_mono$Sequence, "PGT121_LC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "PGT121_LC", mab_number = "single")
PGDM1400_LC_mono <- tibble(coverage = get_coverage_percent(All_peptides_mono$Sequence, "PGDM1400_LC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "PGDM1400_LC", mab_number = "single")

h9C12_LC_poly <- tibble(coverage = get_coverage_percent(All_peptides_poly$Sequence, "h9C12_LC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "h9C12_LC", mab_number = "multiple")
Brimab_LC_poly <- tibble(coverage = get_coverage_percent(All_peptides_poly$Sequence, "Brimab_LC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "Brimab_LC", mab_number = "multiple")
Umab_LC_poly <- tibble(coverage = get_coverage_percent(All_peptides_poly$Sequence, "Umab_LC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "Umab_LC", mab_number = "multiple")
PGT121_LC_poly <- tibble(coverage = get_coverage_percent(All_peptides_poly$Sequence, "PGT121_LC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "PGT121_LC", mab_number = "multiple")
PGDM1400_LC_poly <- tibble(coverage = get_coverage_percent(All_peptides_poly$Sequence, "PGDM1400_LC", annotation = cdr3, mode = "both"), type = str_to_upper(names(coverage)), mab_name = "PGDM1400_LC", mab_number = "multiple")

coverage_lc_mab_number <- bind_rows(h9C12_LC_mono, Brimab_LC_mono, Umab_LC_mono, PGT121_LC_mono, PGDM1400_LC_mono, h9C12_LC_poly, Brimab_LC_poly, Umab_LC_poly, PGT121_LC_poly, PGDM1400_LC_poly)
coverage_lc_mab_number$type <- str_replace_all(coverage_lc_mab_number$type, "VDJ", "VJ")
```

```{r fig.height=4, fig.width=8}
ggplot(data = coverage_hc_mab_number, aes(x = factor(mab_number, levels = c("single", "multiple")), y = coverage)) +
  geom_col(fill = "#6a3e37") +
  facet_grid(factor(type, levels = c("VDJ", "CDR3"))~factor(mab_name, levels = HC_names)) +
  scale_y_continuous(limits = c(0,120), breaks = c(0,25,50,75,100)) +
  geom_text(aes(label = round(coverage,2), vjust = -0.2), size = 3) +
  theme_classic() +
  theme(text = element_text(size = 12), strip.text.x = element_blank()) +
  labs(x = "Number of spike-in mAbs", y = "Sequence coverage (%)")

#ggsave("./figures/coverage_Casanovo_HC_mab_number.pdf", height = 4, width = 8, dpi = 600)
```

```{r fig.height=4, fig.width=8}
ggplot(data = coverage_lc_mab_number, aes(x = factor(mab_number, levels = c("single", "multiple")), y = coverage)) +
  geom_col(fill = "#6a3e37") +
  facet_grid(factor(type, levels = c("VJ", "CDR3"))~factor(mab_name, levels = LC_names)) +
  scale_y_continuous(limits = c(0,120), breaks = c(0,25,50,75,100)) +
  geom_text(aes(label = round(coverage,2), vjust = -0.2), size = 3) +
  theme_classic() +
  theme(text = element_text(size = 12), strip.text.x = element_blank()) +
  labs(x = "Number of spike-in mAbs", y = "Sequence coverage (%)")

#ggsave("./figures/coverage_Casanovo_LC_mab_number.pdf", height = 4, width = 8, dpi = 600)
```
