---
title: "Peptide overlap"
author: "Khang"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F, message=F)
library(readxl)
library(seqinr)
library(tidyverse)
library(reshape2)
library(forcats)
library(RColorBrewer)
library(kableExtra)
library(gridExtra)
library(ggvenn)
```

# Read in the filtered peptide list from the main dataset
```{r}
MQ_peptides <- read_tsv("../../../main_dataset/mq_ab_filtered.tsv")
MSF_peptides <- read_tsv("../../../main_dataset/msf_ab_filtered.tsv")
Casanovo_peptides <- read_tsv("../../../main_dataset/casanovo_ab_filtered.tsv")

MQ_peptides$Tool <- "MaxQuant"
MSF_peptides$Tool <- "MSFragger"
Casanovo_peptides$Tool <- "Casanovo"

# Merge all tools together, exclude intensity / search engine score
All_peptides <- rbind(MQ_peptides[,-5], MSF_peptides[,-5], Casanovo_peptides[,-5])

# Get the peptide length
All_peptides$Sequence_length <- nchar(All_peptides$Sequence)

All_peptides$enzyme <- str_replace_all(All_peptides$enzyme, "aspn", "AspN")
All_peptides$enzyme <- str_replace_all(All_peptides$enzyme, "ct", "Ct")
All_peptides$enzyme <- str_replace_all(All_peptides$enzyme, "tryp", "Tryp")
All_peptides$enzyme <- str_replace_all(All_peptides$enzyme, "ct+tryp", "Ct+Tryp")
```

# Import a list of theoretical peptides from the reference mAbs
```{r}
df <- read_tsv("../theoretical_cuttings/theoretical_cuttings.tsv")
cdr3 <- data.frame(read_tsv("../theoretical_cuttings/antibodies_cdr3_variable_full.tsv"))
cdr3$cdr3_start <- str_locate(cdr3$amino_acid_sequence_Vregion, cdr3$amino_acid_sequence_cdr3)[,1]
cdr3$cdr3_end <- str_locate(cdr3$amino_acid_sequence_Vregion, cdr3$amino_acid_sequence_cdr3)[,2]
```

# For each enzyme and ref mAb, check the overlap between the all unique exp peptides vs theoretical peptides
```{r}
# For each enzyme, create a list of unique peptide sequences from exp data
Sum_peptides <- All_peptides %>% group_by(match_ig_type, enzyme) %>% summarise(Unique_seq = unique(Sequence))

test <- list(Set1 = Sum_peptides %>% filter(match_ig_type == "PGDM1400_HC" & enzyme == "Tryp") %>% pull(Unique_seq),
             Set2 = df %>% filter(seq_name == "PGDM1400_HC" & enzyme == "Tryp") %>% pull(subseq))
```

```{r fig.height=4, fig.width=4}
ggvenn(test, auto_scale = T, fill_color = c("gray30", "white"), set_name_color = "white")
#ggsave("./figures/test.pdf", p_test, height = 3, widt = 3, dpi = 600)
```

```{r}
# Rename the mAb names to match
Sum_peptides$match_ig_type <- str_replace_all(Sum_peptides$match_ig_type, "Bri", "Brimab")
Sum_peptides$match_ig_type <- str_replace_all(Sum_peptides$match_ig_type, "Ust", "Umab")

# Create multiple list of 2: theoretical and exp matching enzyme and reference mAb
unique_peptide_exp <- split(Sum_peptides$Unique_seq, list(Sum_peptides$match_ig_type, Sum_peptides$enzyme))
unique_peptide_exp <- unique_peptide_exp[order(names(unique_peptide_exp))]

unique_peptide_theo <- split(df$subseq, list(df$seq_name, df$enzyme))
unique_peptide_theo <- unique_peptide_theo[order(names(unique_peptide_theo))]

test <- list(exp = unique_peptide_exp$Brimab_HC.Ct, theo = unique_peptide_theo$Brimab_HC.Ct)
```

```{r fig.height=4, fig.width=4}
p_overlap <- map2(.x = unique_peptide_theo, .y = unique_peptide_exp, function(x,y) 
  ggvenn(list(theo = x, exp = y), auto_scale = T, fill_color = c("white","gray30"), set_name_color = "white") +
  scale_x_continuous(expand = expansion(mult = .2)) + scale_y_continuous(expand = expansion(mult = .2)))

p_overlap

#map2(p_overlap, names(p_overlap), function(x,y) ggsave(paste0("./figures/",y,".pdf"), x, height = 4, width = 4, dpi = 600))
```

