---
title: "MSF: data preprocessing"
output: pdf_document
---

```{r setup, include=FALSE}
source("/storage/mariiac/msms_figures/my_config.R")
```

# Download the peptides.txt files for each run and enzyme from google drive

```{r}
# path <- paste0("~/MSMS_raw_data_cleaned/MSF_db_search_output", 
#        outer(paste0("/run", 1:4, "/"), 
#              c("aspn", "ct", "tryp", "ct+tryp"), 
#              paste0), 
#        "/combined_peptide.tsv")
# 
# mq_gfiles <- drive_get(path)
```

```{r}
# path_out <- "~/bioinf/MSMS/igor_MQ_2130_MSF/MSF_output/"
# 
# for (i in 1:nrow(mq_gfiles)) {
#   fpath <- mq_gfiles[i, ]$path
#   fid <- mq_gfiles[i, ]$id
#   run <- unlist(strsplit(fpath, "/"))[4]
#   enzyme <- unlist(strsplit(fpath, "/"))[5]
#   drive_download(file = fid, 
#                  overwrite = T, 
#                  path = paste0(path_out, run, "_", enzyme, "_peptides.txt"))
#}
```


# Combine MSF output in one file

```{r, message=F}

peptides_files <- list.files(path = file.path(data_path, "MSF_raw"), 
                             full.names = T, pattern = ".txt")

df <- data.frame()
for (i in 1:length(peptides_files)) {
  pfile <- peptides_files[i]
  df_tmp <- data.frame(read_tsv(pfile))
  df_tmp$cutting <- unlist(strsplit(basename(pfile), "_"))[2]

  df_tmp <- df_tmp[,  c("Peptide.Sequence", "cutting", 
                      colnames(df_tmp)[grepl("_1.Intensity", colnames(df_tmp), fixed = TRUE)])]

  df_tmp <- melt(df_tmp, id=c("Peptide.Sequence", "cutting"))
  colnames(df_tmp) <- c("Sequence", "Protease", "Rawfilenumber", "intensity")
  df_tmp$run <- unlist(strsplit(basename(pfile), "_"))[1]
  df_tmp$Rawfilenumber <- str_remove(df_tmp$Rawfilenumber, "_1.Intensity")
  df_tmp <- df_tmp[df_tmp$intensity > 0, ]

  df <- rbind(df, df_tmp)
}

df <- as.data.frame(df)
df <- rename_enzymes(df) 

write_tsv(df, file.path(data_path, "MSF_raw/msf_merged.tsv"))

```

# Preprocess MSF files

```{r}
df <- read_tsv(file.path(data_path, "MSF_raw/msf_merged.tsv"))
cdr3 <- data.frame(read_tsv(file.path(metadata_path, "antibodies_cdr3_variable_full.tsv")))

df_res <- preprocess(df, cdr3, cdr3_min_overlap=3)

write_tsv(df_res, file.path(data_path, "msf_ab_annotated.tsv"))
```


