---
title: "Fig 3"
output: pdf_document
---

```{r setup, include=FALSE}
source("/storage/mariiac/msms_figures/my_config.R")
```

```{r}
df <- read_tsv(file.path(data_path, "all_peptides_preprocessed.tsv"))
df <- df[df$is_not_contamination, ]
```

```{r}
replicate_subsets <- unlist(lapply(1:4, combn, x = paste0("run", 1:4), simplify = FALSE), recursive = FALSE)

```



```{r}
res <- data.frame()
cdr3 <- read_tsv(file.path(metadata_path, "antibodies_cdr3_variable_full.tsv"))

sample_info <- read_tsv(file.path(metadata_path, "detailed_sample_description.tsv"))

for (i in 1:length(replicate_subsets)) {
  for (sample in 1:70) {
    abs_all <- c("h9C12-Q97A_HC", "h9C12-WT_HC",   "Brimab_HC",     "PGDM1400_HC",   "PGT121_HC",     "Umab_HC")
    abs_ref <- abs_all[unlist(sample_info[sample, abs_all])]
    
    subset <- replicate_subsets[[i]]
    df_tmp <- df[df$run %in% subset & df$Sample == sample, ]
    
    if (length(abs_ref)) {
      coverage <- sapply(X = abs_ref, FUN = get_coverage_percent, 
                       peptides_vector = df_tmp$Sequence, annotation = cdr3, mode = "both")
      coverage <- data.frame(t(coverage))
      coverage$subset <- paste0(subset, collapse = " ")
      coverage$sequence_name <- rownames(coverage)
      coverage$sample <- sample
      res <- rbind(res, coverage)
    }
  }
  
}

res$subset <- factor(res$subset,
    levels = unlist(lapply(replicate_subsets, function(x) {paste0(x, collapse = " ")})) ,ordered = TRUE)


```

```{r}
concentrations <- data.frame(read_tsv(file.path(metadata_path, "concentration_matrix.tsv")))
concentrations$sample <- 1:70
colnames(concentrations)[1:2] <- c("h9C12-Q97A", "h9C12-WT")
concentrations <- melt(concentrations, id.vars = "sample")
concentrations$sequence_name <- paste0(concentrations$variable, "_HC")

res <- merge(res, concentrations, by = c("sample", "sequence_name"), all.x = T)

res <- res[res$subset %in% c("run1", "run2", "run3", "run4", "run1 run2 run3 run4"), ]
```

```{r, fig.height=7, fig.width = 8}


g <- ggplot(res, aes(x = as.factor(subset), y = vdj, fill = as.factor(subset))) +
  geom_boxplot(outlier.shape = NA) +
  facet_grid(factor(res$sequence_name, levels = HC_names) ~value) +
  geom_point(pch = 21, position = position_jitterdodge()) +
  theme_bw() +
  scale_fill_manual(values = c("#1F1F1F", "#4A4B4B", "#6F6F6F", "#A4A4A4", "#e6007e")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

plot(g)
  
  png(file.path(fig3_path, "HC_vdj.png"), 
      width = 7, height = 8, units = 'in', res = 600)
  plot(g)
  dev.off()
```



```{r, fig.height=7, fig.width = 8}

g <- ggplot(res, aes(x = as.factor(subset), y = cdr3, fill = as.factor(subset))) +
  geom_boxplot(outlier.shape = NA) +
  facet_grid(factor(res$sequence_name, levels = HC_names) ~value) +
  geom_point(pch = 21, position = position_jitterdodge()) +
  #geom_line(stat = "summary", fun = median, aes(group = as.factor(subset))) +
  theme_bw() +
  scale_fill_manual(values = c("#2F2F2F", "#4A4B4B", "#6F6F6F", "#A4A4A4", "#e6007e")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

plot(g)
  
  png(file.path(fig3_path, "HC_cdr3.png"), 
      width = 7, height = 8, units = 'in', res = 600)
  plot(g)
  dev.off()

# ggplot(res, aes(x = subset, y = cdr3)) +
#   geom_boxplot() +
#   facet_grid(sequence_name~.) +
#   geom_jitter(aes(color = as.factor(value))) +
#   theme_bw() +
#   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```



#### light chain

```{r}
res <- data.frame()
cdr3 <- read_tsv(file.path(metadata_path, "antibodies_cdr3_variable_full.tsv"))

sample_info <- read_tsv(file.path(metadata_path, "detailed_sample_description.tsv"))

for (i in 1:length(replicate_subsets)) {
  for (sample in 1:70) {
    abs_all <- c("h9C12_LC", "Brimab_LC",     "PGDM1400_LC",   "PGT121_LC",     "Umab_LC")
    abs_ref <- abs_all[unlist(sample_info[sample, abs_all])]
    
    subset <- replicate_subsets[[i]]
    df_tmp <- df[df$run %in% subset & df$Sample == sample, ]
    
    if (length(abs_ref)) {
      coverage <- sapply(X = abs_ref, FUN = get_coverage_percent, 
                       peptides_vector = df_tmp$Sequence, annotation = cdr3, mode = "both")
      coverage <- data.frame(t(coverage))
      coverage$subset <- paste0(subset, collapse = " ")
      coverage$sequence_name <- rownames(coverage)
      coverage$sample <- sample
      res <- rbind(res, coverage)
    }
  }
  
}

res$subset <- factor(res$subset,
    levels = unlist(lapply(replicate_subsets, function(x) {paste0(x, collapse = " ")})) ,ordered = TRUE)


```

```{r}
concentrations <- data.frame(read_tsv(file.path(metadata_path, "concentration_matrix.tsv")))
concentrations$sample <- 1:70
colnames(concentrations)[1:2] <- c("h9C12", "h9C12")
concentrations <- melt(concentrations, id.vars = "sample")
concentrations$sequence_name <- paste0(concentrations$variable, "_LC")

res <- merge(res, concentrations, by = c("sample", "sequence_name"), all.x = T)

res <- res[res$subset %in% c("run1", "run2", "run3", "run4", "run1 run2 run3 run4"), ]
res <- res[res$value > 0,]
```

```{r, fig.height=7, fig.width = 8}


g <- ggplot(res, aes(x = as.factor(subset), y = vdj, fill = as.factor(subset))) +
  geom_boxplot(outlier.shape = NA) +
  facet_grid(factor(res$sequence_name, levels = LC_names) ~value) +
  geom_point(pch = 21, position = position_jitterdodge()) +
  theme_bw() +
  scale_fill_manual(values = c("#1F1F1F", "#4A4B4B", "#6F6F6F", "#A4A4A4", "#e6007e")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

plot(g)
  
  png(file.path(fig3_path, "LC_vdj.png"), 
      width = 7, height = 8, units = 'in', res = 600)
  plot(g)
  dev.off()
```

```{r, fig.height=7, fig.width = 8}
g <- ggplot(res, aes(x = as.factor(subset), y = cdr3, fill = as.factor(subset))) +
  geom_boxplot(outlier.shape = NA) +
  facet_grid(factor(res$sequence_name, levels = LC_names) ~value) +
  geom_point(pch = 21, position = position_jitterdodge()) +
  #geom_line(stat = "summary", fun = median, aes(group = as.factor(subset))) +
  theme_bw() +
  scale_fill_manual(values = c("#2F2F2F", "#4A4B4B", "#6F6F6F", "#A4A4A4", "#e6007e")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

plot(g)
  
  png(file.path(fig3_path, "LC_cdr3.png"), 
      width = 7, height = 8, units = 'in', res = 600)
  plot(g)
  dev.off()
```


#### old stuff




```{r}
library(dplyr)

res <- data.frame()

for (i in 1:length(replicate_subsets)) {
  subset <- replicate_subsets[[i]]
  df_tmp <- df[df$run %in% subset, ]
  
  peptides <- sapply(X = cdr3$sequence_name, FUN = function(x) {length(unique(df_tmp[df_tmp$match_ig_type == x,]$Sequence))})
  peptides <- data.frame(peptides = peptides)
  peptides$subset <- paste0(subset, collapse = " ")
  peptides$sequence_name <- rownames(peptides)
  res <- rbind(res, peptides)
}

```

```{r}
res$subset <- factor(res$subset,
    levels = unlist(lapply(replicate_subsets, function(x) {paste0(x, collapse = " ")})) ,ordered = TRUE)

ggplot(res[str_detect(res$sequence_name, "HC"),], aes(x = subset, y = peptides)) +
  geom_boxplot() +
  geom_jitter() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


```{r}

sample_info <- read_tsv(file.path(metadata_path, "detailed_sample_description.tsv"))

paired_samples <- data.frame(blood_sample = c(2, 10, 18, 26, 
                  4, 12, 20, 28, 
                  6, 14, 22, 30, 
                  55:58), 
                  no_blood_sample = c(36:39, 
                     40:43, 
                     44:47, 
                     8, 16, 24, 35))

res <- data.frame()

for (i in 1:nrow(paired_samples)) {
  blood <- paired_samples$blood_sample[i]
  no_blood <- paired_samples$no_blood_sample[i]
  
  df_tmp_blood <- df[df$Sample ==  blood, ]
  df_tmp_no_blood <- df[df$Sample ==  no_blood, ]
  
  idx_HC <- unlist(sample_info[sample_info$Sample == blood, which(str_detect(colnames(sample_info), "HC"))])
  HC <- colnames(sample_info)[str_detect(colnames(sample_info), "HC")][idx_HC] 
  
  idx_LC <- unlist(sample_info[sample_info$Sample == blood, which(str_detect(colnames(sample_info), "LC"))])
  LC <- colnames(sample_info)[str_detect(colnames(sample_info), "LC")][idx_LC] 
  
  abs <- c(HC, LC)
  
  coverage_blood <- data.frame(t(sapply(X = abs, FUN = get_coverage_percent, 
                     peptides_vector = df_tmp_blood$Sequence, annotation = cdr3, mode = "both")))
  colnames(coverage_blood) <- c("vdj_blood", "cdr3_blood")
  coverage_blood$sample <- blood
  coverage_blood$Sequence <- rownames(coverage_blood)
  
  coverage_no_blood <-  data.frame(data.frame(t(sapply(X = abs, FUN = get_coverage_percent, 
                     peptides_vector = df_tmp_no_blood$Sequence, annotation = cdr3, mode = "both"))))
  colnames(coverage_no_blood) <- c("vdj_no_blood", "cdr3_no_blood")
  coverage_no_blood$sample <- no_blood
  res_tmp <- cbind(coverage_blood, coverage_no_blood)
  res <- rbind(res, res_tmp)
}

```

```{r}
ggplot(res[str_detect(res$Sequence, "HC"), c("vdj_no_blood", "vdj_blood")], aes(x=vdj_no_blood, y=vdj_blood)) +
  geom_point() +
  theme_bw() +
  xlim(0, 100) +
  ylim(0, 100) +
  geom_abline(slope=1, intercept = 0, color = "red")
  
```

```{r}
ggplot(res[str_detect(res$Sequence, "HC"), c("cdr3_no_blood", "cdr3_blood")], aes(x=cdr3_no_blood, y=cdr3_blood)) +
  geom_point() +
  theme_bw() +
  xlim(0, 100) +
  ylim(0, 100) +
  geom_abline(slope=1, intercept = 0, color = "red")
```

=================






























```{r}

get_coverage_per_run <- function(df) {
  res <- data.frame()
cdr3 <- read_tsv(file.path(metadata_path, "antibodies_cdr3_variable_full.tsv"))

for (i in 1:length(replicate_subsets)) {
  subset <- replicate_subsets[[i]]
  df_tmp <- df[df$run %in% subset, ]
  res_full <- sapply(X = cdr3$sequence_name, FUN = get_coverage_percent, s_vector = df_tmp$Sequence, cdr3 = cdr3)
  res_cdr3 <- sapply(X = cdr3$sequence_name, FUN = get_cdr3_coverage_percent, s_vector = df_tmp$Sequence, cdr3 = cdr3)
  res_tmp <- data.frame(subset = paste0(subset, collapse = " "),
                        full_coverage = res_full, 
                        cdr3_coverage = res_cdr3, 
                        sequence_name = str_remove(names(res_full), ".amino_acid_sequence_Vregion"))
  res <- rbind(res, res_tmp)
}
return(res)
}
```

```{r}
res_casanovo <- get_coverage_per_run(df[df$tool == "Casanovo", ])
res_casanovo$tool <- "Casanovo"
res_MQ <- get_coverage_per_run(df[df$tool == "MaxQuant", ])
res_MQ$tool <- "MQ"
res_MSF <- get_coverage_per_run(df[df$tool == "MSFragger", ])
res_MSF$tool <- "MSF"

res_per_tool <- rbind(res_casanovo, res_MQ, res_MSF)
```

```{r, fig.width = 10}
ggplot(res_per_tool[str_detect(res_per_tool$sequence_name, "HC"),], aes(x = subset, y = full_coverage, fill=tool)) +
  geom_boxplot() +
  geom_jitter(position=position_dodge(0.8)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


```{r, fig.width = 10}
ggplot(res_per_tool[str_detect(res_per_tool$sequence_name, "HC"),], aes(x = subset, y = cdr3_coverage, fill = tool)) +
  geom_boxplot() +
  geom_jitter(position=position_dodge(0.8)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

