---
title: "Figure 3"
output: pdf_document
---

```{r setup, include=FALSE}
source("../my_config.R")
library(ggbeeswarm)
```

```{r include=FALSE}
#Read the filtered data and removed peptides labelled contaminations
df <- read_tsv(file.path(data_path, "all_peptides_preprocessed.tsv"))
df <- df[df$is_not_contamination, ]

cdr3 <- read_tsv(file.path(metadata_path, "antibodies_cdr3_variable_full.tsv"))
sample_info <- read_tsv(file.path(metadata_path, "detailed_sample_description.tsv"))

# Create combinations of replicates
replicate_subsets <- unlist(lapply(1:4, combn, x = paste0("run", 1:4), simplify = FALSE), recursive = FALSE)
```

```{r}
res <- data.frame()
# Calculate coverage for each sample, iterate by rep combn
for (i in 1:length(replicate_subsets)) {
  for (sample in 1:70) {
    abs_all <- c("h9C12-Q97A_HC", "h9C12-WT_HC", "Brimab_HC", "PGDM1400_HC", "PGT121_HC", "Umab_HC")
    # Use only the mAb that should be in that sample as ref
    abs_ref <- abs_all[unlist(sample_info[sample, abs_all])]
    # choose the correct runs and filter for the correct sample
    subset <- replicate_subsets[[i]]
    df_tmp <- df[df$run %in% subset & df$Sample == sample, ]
    
    if (length(abs_ref)) {
      coverage <- sapply(X = abs_ref, FUN = get_coverage_percent, 
                       peptides_vector = df_tmp$Sequence, annotation = cdr3, mode = "both")
      coverage <- data.frame(t(coverage))
      coverage$subset <- paste0(subset, collapse = " ")
      coverage$sequence_name <- rownames(coverage)
      coverage$sample <- sample
      res <- rbind(res, coverage)
    }
  }
}

res$subset <- factor(res$subset,
    levels = unlist(lapply(replicate_subsets, function(x) {paste0(x, collapse = " ")})) ,ordered = TRUE)
```

```{r}
concentrations <- data.frame(read_tsv(file.path(metadata_path, "concentration_matrix.tsv")))
concentrations$sample <- 1:70
colnames(concentrations)[1:2] <- c("h9C12-Q97A", "h9C12-WT")
concentrations <- melt(concentrations, id.vars = "sample")
concentrations$sequence_name <- paste0(concentrations$variable, "_HC")

res <- merge(res, concentrations, by = c("sample", "sequence_name"), all.x = T)
# Count the number of runs merged
res$subset_count <- str_count(res$subset, "run")
res$sequence_name <- factor(res$sequence_name, levels = HC_names)

# Filter for only 1 run and all 4 runs combined
res_2 <- res %>% filter(subset_count == 1 | subset_count == 4)
res_2$subset <- factor(res_2$subset, levels = c("run1", "run2", "run3", "run4", "run1 run2 run3 run4"))

# calculate the median and iqr range
res_2_med <- res_2 %>%  group_by(sequence_name, subset, value) %>% summarise(med_vdj = median(vdj), med_cdr3 = median(cdr3)) %>% arrange(sequence_name, value)
res_2_med$sequence_name <- factor(res_2_med$sequence_name, levels = HC_names)

res_2_med_range <- res_2_med %>% group_by(value, sequence_name) %>% summarise(med_vdj_range = max(med_vdj) - min(med_vdj), med_cdr3_range = max(med_cdr3) - min(med_cdr3)) %>% arrange(value, med_cdr3_range)

res_2_iqr <- res_2 %>%  group_by(sequence_name, subset, value) %>% summarise(iqr_vdj = IQR(vdj), iqr_cdr3 = IQR(cdr3)) %>% arrange(subset, value)

res_2_iqr_mean <- res_2_iqr %>% group_by(sequence_name, value) %>% summarise(mean_iqr_vdj = mean(iqr_vdj), mean_iqr_cdr3 = mean(iqr_cdr3)) %>% arrange(value, mean_iqr_cdr3)

color_x_tick <- ifelse(res_2$subset == "run3", "#e6007e", "black")
```

# Panel A,B: coverage of individual replicates and all replicates combined
```{r fig.height=7, fig.width=6}
p_vdj <- ggplot(res_2, aes(x = subset, y = vdj, fill = subset)) +
  geom_boxplot(width = 0.5, outlier.shape = NA) +
  scale_x_discrete(labels = c("1", "2", "3", "4", "Σ")) +
  scale_fill_manual(values = c("#969696", "#bdbdbd", "#d9d9d9", "#ffffff", "#e6007e")) +
  facet_grid(sequence_name ~ value) +
  geom_beeswarm(pch = 21, size = 0.5, cex = 2, corral = "wrap", corral.width = 0.9) +
  geom_text(data = res_2_med, aes(y = -10, label = round(med_vdj, 2)), size = 2) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, color = color_x_tick),
        legend.position = "none",
        strip.text.x = element_blank(), strip.text.y = element_blank()) +
  labs(x = "Experimental replicate", y = "VDJ coverage (%)")

p_vdj

#ggsave("./figure/HC_vdj.png", p_vdj, height = 7, width = 6, dpi = 600)
```

```{r fig.height=7, fig.width=6}
p_cdr3 <- ggplot(res_2, aes(x = subset, y = cdr3, fill = subset)) +
  geom_boxplot(width = 0.5, outlier.shape = NA) +
  scale_x_discrete(labels = c("1", "2", "3", "4", "Σ")) +
  scale_fill_manual(values = c("#969696", "#bdbdbd", "#d9d9d9", "#ffffff", "#e6007e")) +
  facet_grid(sequence_name ~ value) +
  geom_beeswarm(pch = 21, size = 0.5, cex = 2, corral = "wrap", corral.width = 0.9) +
  geom_text(data = res_2_med, aes(y = -10, label = round(med_cdr3, 2)), size = 2) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, color = color_x_tick),
        legend.position = "none",
        strip.text.x = element_blank(), strip.text.y = element_blank()) +
  labs(x = "Experimental replicate", y = "CDRH3 coverage (%)")

p_cdr3

#ggsave("./figure/HC_cdr3.png", p_cdr3, height = 7, width = 6, dpi = 600)
```

# Panel C,D: coverage of cumulatively merged replicates
```{r}
# calculate the median and iqr range
res_med <- res %>%  group_by(sequence_name, subset_count, value) %>% summarise(med_vdj = median(vdj), med_cdr3 = median(cdr3)) %>% arrange(sequence_name, value)
res_med$sequence_name <- factor(res_med$sequence_name, levels = HC_names)

res_med_gap <- res_med %>% filter(subset_count == 1 | subset_count == 4) %>% group_by(sequence_name, value) %>% summarise(gap_med_vdj = max(med_vdj) - min(med_vdj), gap_med_cdr3 = max(med_cdr3) - min(med_cdr3)) %>% arrange(value, gap_med_vdj)

res_med_range <- res_med %>% group_by(value, sequence_name) %>% summarise(med_vdj_range = max(med_vdj) - min(med_vdj), med_cdr3_range = max(med_cdr3) - min(med_cdr3)) %>% arrange(value, med_cdr3_range)

res_med_step <- res_med %>% group_by(sequence_name, value) %>% summarise(med_vdj_diff = diff(med_vdj), med_cdr3_diff = diff(med_cdr3)) %>% group_by(sequence_name, value) %>% summarise(avg_med_vdj_diff = mean(med_vdj_diff), avg_med_cdr3_diff = mean(med_cdr3_diff)) %>% arrange(value, avg_med_vdj_diff)

res_iqr <- res %>% filter(!subset == "run1 run2 run3 run4") %>%  group_by(sequence_name, subset, value) %>% summarise(iqr_vdj = IQR(vdj), iqr_cdr3 = IQR(cdr3)) %>% arrange(subset, value)

res_iqr_mean <- res_iqr %>% group_by(sequence_name, value) %>% summarise(mean_iqr_vdj = mean(iqr_vdj), mean_iqr_cdr3 = mean(iqr_cdr3)) %>% arrange(value, mean_iqr_cdr3)
```

```{r fig.height=7, fig.width=6}
p_vdj_merged <- ggplot(res, aes(x = as.factor(subset_count), y = vdj, fill = as.factor(subset_count))) +
  geom_boxplot(width = 0.5, outlier.shape = NA) +
  facet_grid(sequence_name ~ value, labeller = labeller(value = label_value)) +
  geom_beeswarm(pch = 21, size = 0.5, cex = 2, corral = "wrap", corral.width = 0.9) +
  geom_text(data = res_med, aes(y = -10, label = round(med_vdj,2)), size = 2) +
  theme_bw() +
  scale_fill_manual(values = hcl.colors(n = 7, palette = "PuRd", rev = TRUE)[2:5]) +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5), legend.position = "none",
        strip.text.x = element_blank(), strip.text.y = element_blank()) +
  labs(x = "Number of experimental replicates merged", y = "VDJ coverage (%)")

p_vdj_merged

#ggsave("./figure/HC_vdj_merged.png", p_vdj_merged, height = 7, width = 6, dpi = 600)
```

```{r fig.height=7, fig.width=6}
p_cdr3_merged <- ggplot(res, aes(x = as.factor(subset_count), y = cdr3, fill = as.factor(subset_count))) +
  geom_boxplot(width = 0.5, outlier.shape = NA) +
  facet_grid(sequence_name ~ value, labeller = labeller(value = label_value)) +
  geom_beeswarm(pch = 21, size = 0.5, cex = 2, corral = "wrap", corral.width = 0.9) +
  geom_text(data = res_med, aes(y = -10, label = round(med_cdr3,2)), size = 2) +
  theme_bw() +
  scale_fill_manual(values = hcl.colors(n = 7, palette = "PuRd", rev = TRUE)[2:5]) +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5), legend.position = "none",
        strip.text.x = element_blank(), strip.text.y = element_blank()) +
  labs(x = "Number of experimental replicates merged", y = "CDRH3 coverage (%)")

p_cdr3_merged

#ggsave("./figure/HC_CDR3_merged.png", p_cdr3_merged, height = 7, width = 6, dpi = 600)
```

# Light chain supp figure

```{r}
res <- data.frame()

for (i in 1:length(replicate_subsets)) {
  for (sample in 1:70) {
    abs_all <- c("h9C12_LC", "Brimab_LC", "PGDM1400_LC", "PGT121_LC", "Umab_LC")
    abs_ref <- abs_all[unlist(sample_info[sample, abs_all])]
    
    subset <- replicate_subsets[[i]]
    df_tmp <- df[df$run %in% subset & df$Sample == sample, ]
    
    if (length(abs_ref)) {
      coverage <- sapply(X = abs_ref, FUN = get_coverage_percent, 
                       peptides_vector = df_tmp$Sequence, annotation = cdr3, mode = "both")
      coverage <- data.frame(t(coverage))
      coverage$subset <- paste0(subset, collapse = " ")
      coverage$sequence_name <- rownames(coverage)
      coverage$sample <- sample
      res <- rbind(res, coverage)
    }
  }
}

res$subset <- factor(res$subset,
    levels = unlist(lapply(replicate_subsets, function(x) {paste0(x, collapse = " ")})) ,ordered = TRUE)
```

```{r}
concentrations <- data.frame(read_tsv(file.path(metadata_path, "concentration_matrix.tsv")))
# For the light chain, since h9C12-WT and h9C12-Q97 are the same, take the higher value of the two cols
concentrations <- concentrations %>% mutate(h9C12 = pmax(concentrations$h9C12.Q97A, concentrations$h9C12.WT)) %>%
  select(-c(1:2)) %>% relocate(h9C12)
concentrations$sample <- 1:70
concentrations <- melt(concentrations, id.vars = "sample")
concentrations$sequence_name <- paste0(concentrations$variable, "_LC")

# Fix the concentration in the concentration matrix for h9C12
concentrations$value[c(2,36)] <- 1
concentrations$value[c(10,37)] <- 10
concentrations$value[c(18,38)] <- 100
concentrations$value[c(26,39)] <- 1000

res <- merge(res, concentrations, by = c("sample", "sequence_name"), all.x = T)

# Count the number of runs merged
res$subset_count <- str_count(res$subset, "run")
res$sequence_name <- factor(res$sequence_name, levels = LC_names)

# Filter for only 1 run and all 4 runs combined
res_2 <- res %>% filter(subset_count == 1 | subset_count == 4)
res_2$subset <- factor(res_2$subset, levels = c("run1", "run2", "run3", "run4", "run1 run2 run3 run4"))

# calculate the median and iqr range
res_2_med <- res_2 %>%  group_by(sequence_name, subset, value) %>% summarise(med_vdj = median(vdj), med_cdr3 = median(cdr3)) %>% arrange(sequence_name, value)
res_2_med$sequence_name <- factor(res_2_med$sequence_name, levels = LC_names)

color_x_tick <- ifelse(res_2$subset == "run3", "#e6007e", "black")
```

```{r fig.height=7, fig.width=6}
p_vdj <- ggplot(res_2, aes(x = subset, y = vdj, fill = subset)) +
  geom_boxplot(width = 0.5, outlier.shape = NA) +
  scale_x_discrete(labels = c("1", "2", "3", "4", "Σ")) +
  scale_fill_manual(values = c("#969696", "#bdbdbd", "#d9d9d9", "#ffffff", "#e6007e")) +
  facet_grid(sequence_name ~ value) +
  geom_beeswarm(pch = 21, size = 0.5, cex = 2, corral = "wrap", corral.width = 0.9) +
  geom_text(data = res_2_med, aes(y = -10, label = round(med_vdj, 2)), size = 2) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, color = color_x_tick),
        legend.position = "none",
        strip.text.x = element_blank(), strip.text.y = element_blank()
        ) +
  labs(x = "Experimental replicate", y = "VJ coverage (%)")

p_vdj

#ggsave("./figure/LC_vdj.png", p_vdj, height = 7, width = 6, dpi = 600)
```

```{r fig.height=7, fig.width=6}
p_cdr3 <- ggplot(res_2, aes(x = subset, y = cdr3, fill = subset)) +
  geom_boxplot(width = 0.5, outlier.shape = NA) +
  scale_x_discrete(labels = c("1", "2", "3", "4", "Σ")) +
  scale_fill_manual(values = c("#969696", "#bdbdbd", "#d9d9d9", "#ffffff", "#e6007e")) +
  facet_grid(sequence_name ~ value) +
  geom_beeswarm(pch = 21, size = 0.5, cex = 2, corral = "wrap", corral.width = 0.9) +
  geom_text(data = res_2_med, aes(y = -10, label = round(med_cdr3, 2)), size = 2) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, color = color_x_tick),
        legend.position = "none",
        strip.text.x = element_blank(), strip.text.y = element_blank()) +
  labs(x = "Experimental replicate", y = "CDRL3 coverage (%)")

p_cdr3

#ggsave("./figure/LC_cdr3.png", p_cdr3, height = 7, width = 6, dpi = 600)
```

```{r}
# calculate the median and iqr range
res_med <- res %>% group_by(sequence_name, subset_count, value) %>% summarise(med_vdj = median(vdj), med_cdr3 = median(cdr3)) %>% arrange(sequence_name, value)
res_med$sequence_name <- factor(res_med$sequence_name, levels = LC_names)

res_med_range <- res_med %>% group_by(value, sequence_name) %>% summarise(med_vdj_range = max(med_vdj) - min(med_vdj), med_cdr3_range = max(med_cdr3) - min(med_cdr3)) %>% arrange(value, med_cdr3_range)

res_iqr <- res %>% filter(!subset == "run1 run2 run3 run4") %>%  group_by(sequence_name, subset, value) %>% summarise(iqr_vdj = IQR(vdj), iqr_cdr3 = IQR(cdr3)) %>% arrange(subset, value)

res_iqr_mean <- res_iqr %>% group_by(sequence_name, value) %>% summarise(mean_iqr_vdj = mean(iqr_vdj), mean_iqr_cdr3 = mean(iqr_cdr3)) %>% arrange(value, mean_iqr_cdr3)
```

```{r fig.height=7, fig.width=6}
p_vdj_merged <- ggplot(res, aes(x = as.factor(subset_count), y = vdj, fill = as.factor(subset_count))) +
  geom_boxplot(width = 0.5, outlier.shape = NA) +
  facet_grid(sequence_name ~ value, labeller = labeller(value = label_value)) +
  geom_beeswarm(pch = 21, size = 0.5, cex = 2, corral = "wrap", corral.width = 0.9) +
  geom_text(data = res_med, aes(y = -10, label = round(med_vdj,2)), size = 2) +
  theme_bw() +
  scale_fill_manual(values = hcl.colors(n = 7, palette = "PuRd", rev = TRUE)[2:5]) +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5), legend.position = "none",
        strip.text.x = element_blank(), strip.text.y = element_blank()) +
  labs(x = "Number of experimental replicates merged", y = "VJ coverage (%)")

p_vdj_merged

#ggsave("./figure/LC_vdj_merged.png", p_vdj_merged, height = 7, width = 6, dpi = 600)
```

```{r fig.height=7, fig.width=6}
p_cdr3_merged <- ggplot(res, aes(x = as.factor(subset_count), y = cdr3, fill = as.factor(subset_count))) +
  geom_boxplot(width = 0.5, outlier.shape = NA) +
  facet_grid(sequence_name ~ value, labeller = labeller(value = label_value)) +
  geom_beeswarm(pch = 21, size = 0.5, cex = 2, corral = "wrap", corral.width = 0.9) +
  geom_text(data = res_med, aes(y = -10, label = round(med_cdr3,2)), size = 2) +
  theme_bw() +
  scale_fill_manual(values = hcl.colors(n = 7, palette = "PuRd", rev = TRUE)[2:5]) +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5), legend.position = "none",
        strip.text.x = element_blank(), strip.text.y = element_blank()) +
  labs(x = "Number of experimental replicates merged", y = "CDRL3 coverage (%)")

p_cdr3_merged

#ggsave("./figure/LC_CDR3_merged.png", p_cdr3_merged, height = 7, width = 6, dpi = 600)
```
