---
title: "MS supp fig peptide numbers"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
source("/Users/khangl/UiO Dropbox/Khang Le Quy/CSI/datasets/csi_datasets/ms_benchmarking/msms_figures/Khang_config.R")
source("/Users/khangl/UiO Dropbox/Khang Le Quy/CSI/datasets/csi_datasets/ms_benchmarking/msms_figures/utils.R")
library(corrplot)
library(ggfortify)
library(GGally)
```

```{r message=FALSE}
cdr3 <- read_tsv(file.path(metadata_path, "antibodies_cdr3_variable_full.tsv"))
sample_info <- read_tsv(file.path(metadata_path, "detailed_sample_description.tsv"))

df <- read_tsv(file.path(data_path, "all_peptides_preprocessed.tsv"))
df <- df[df$is_not_contamination, ]

# Read the sample number and replicates
sample_number <- read_tsv(file.path(metadata_path, "rawfiles_description_wo_blanks.tsv"))
sample_number <- sample_number %>% group_by(Sample, Protease, run) %>% 
  mutate(replicate = row_number())

df <- left_join(df, sample_number[,c(1,5)])
```

# Panel A: Number of unique peptides per experimental replicate

```{r}
n_unique_peptide_vdj <- df %>% group_by(run, match_ig_type, has_blood) %>% summarize(n_peptide = length(unique(Sequence)))
n_unique_peptide_cdr3 <- df %>% filter(is_cdr3_related == TRUE) %>% group_by(run, match_ig_type, has_blood) %>% summarize(n_peptide = length(unique(Sequence)))
```

```{r fig.height=4, fig.width=8}
ggplot(data = n_unique_peptide_vdj %>% filter(str_detect(match_ig_type,"_HC")), aes(x = run, y = n_peptide, fill = run)) +
  geom_col(width = 0.8) +
  geom_text(aes(label = n_peptide), vjust = -0.2) +
  scale_fill_manual(values = c("#48cae4", "#0096c7", "#0077B6", "#03045E")) +
  scale_x_discrete(labels = c("1", "2", "3", "4")) +
  scale_y_continuous(limits = c(0,80)) +
  facet_grid(factor(has_blood, levels = c("TRUE", "FALSE"))~factor(match_ig_type, levels = HC_names)) +
  labs(x = "Experimental replicate", y = "Number of unique peptide sequences") +
  theme_bw() +
  theme(legend.position = "none", strip.text = element_blank())

ggsave("./figures/n_unique_peptide_vdj_hc.pdf", dpi = 600, height = 4, width = 8)
```

```{r fig.height=4, fig.width=6.67}
ggplot(data = n_unique_peptide_vdj %>% filter(str_detect(match_ig_type,"_LC")), aes(x = run, y = n_peptide, fill = run)) +
  geom_col(width = 0.8) +
  geom_text(aes(label = n_peptide), vjust = -0.2) +
  scale_fill_manual(values = c("#48cae4", "#0096c7", "#0077B6", "#03045E")) +
  scale_x_discrete(labels = c("1", "2", "3", "4")) +
  scale_y_continuous(limits = c(0,80)) +
  facet_grid(factor(has_blood, levels = c("TRUE", "FALSE"))~factor(match_ig_type, levels = LC_names)) +
  labs(x = "Experimental replicate", y = "Number of unique peptide sequences") +
  theme_bw() +
  theme(legend.position = "none", strip.text = element_blank())

ggsave("./figures/n_unique_peptide_vdj_lc.pdf", dpi = 600, height = 4, width = 8)
```

```{r fig.height=4, fig.width=8}
ggplot(data = n_unique_peptide_cdr3 %>% filter(str_detect(match_ig_type,"_HC")), aes(x = run, y = n_peptide, fill = run)) +
  geom_col(width = 0.8) +
  geom_text(aes(label = n_peptide), vjust = -0.2) +
  scale_fill_manual(values = c("#48cae4", "#0096c7", "#0077B6", "#03045E")) +
  scale_x_discrete(labels = c("1", "2", "3", "4")) +
  scale_y_continuous(limits = c(0,20)) +
  facet_grid(factor(has_blood, levels = c("TRUE", "FALSE"))~factor(match_ig_type, levels = HC_names)) +
  labs(x = "Experimental replicate", y = "Number of unique peptide sequences") +
  theme_bw() +
  theme(legend.position = "none", strip.text = element_blank())

ggsave("./figures/n_unique_peptide_cdr3_hc.pdf", dpi = 600, height = 4, width = 8)
```

```{r fig.height=4, fig.width=6.67}
ggplot(data = n_unique_peptide_cdr3 %>% filter(str_detect(match_ig_type,"_LC")), aes(x = run, y = n_peptide, fill = run)) +
  geom_col(width = 0.8) +
  geom_text(aes(label = n_peptide), vjust = -0.2) +
  scale_fill_manual(values = c("#48cae4", "#0096c7", "#0077B6", "#03045E")) +
  scale_x_discrete(labels = c("1", "2", "3", "4")) +
  scale_y_continuous(limits = c(0,20)) +
  facet_grid(factor(has_blood, levels = c("TRUE", "FALSE"))~factor(match_ig_type, levels = LC_names)) +
  labs(x = "Experimental replicate", y = "Number of unique peptide sequences") +
  theme_bw() +
  theme(legend.position = "none", strip.text = element_blank())

ggsave("./figures/n_unique_peptide_cdr3_lc.pdf", dpi = 600, height = 4, width = 8)
```

# Panel B: Jaccard overlap of peptide between replicates

```{r include=FALSE}
calc_pairwise_overlaps <- function(sets) {

  vec_name1 <- character()
  vec_name2 <- character()
  vec_num_shared <- integer()
  vec_overlap <- numeric()
  vec_jaccard <- numeric()

  for (name1 in names(sets)) {
    set1 <- sets[[name1]]
    for (name2 in names(sets)) {
      set2 <- sets[[name2]]
      set_intersection <- intersect(set1, set2)
      num_shared <- length(set_intersection)
      overlap <- num_shared / min(length(set1), length(set2))
      jaccard <- num_shared / length(union(set1, set2))

      vec_name1 <- c(vec_name1, name1)
      vec_name2 <- c(vec_name2, name2)
      vec_num_shared <- c(vec_num_shared, num_shared)
      vec_overlap <- c(vec_overlap, overlap)
      vec_jaccard <- c(vec_jaccard, jaccard)
    }
  }

  result <- data.frame(name1 = vec_name1,
                       name2 = vec_name2,
                       num_shared = vec_num_shared,
                       overlap = vec_overlap,
                       jaccard = vec_jaccard,
                       stringsAsFactors = FALSE)
  return(result)
}
```

```{r}
# Make a list of unique peptides (vdj and cdr3) for each replicate
unique_peptides_vdj <- df %>% group_by(run) %>% select(Sequence) %>% group_split()
unique_peptides_vdj <- map(unique_peptides_vdj, function(x) x %>% pull(Sequence) %>% unique())
names(unique_peptides_vdj) <- sort(unique(df$run))

unique_peptides_cdr3 <- df %>% filter(is_cdr3_related == TRUE) %>% group_by(run) %>% select(Sequence) %>% group_split()
unique_peptides_cdr3 <- map(unique_peptides_cdr3, function(x) x %>% pull(Sequence) %>% unique())
names(unique_peptides_cdr3) <- sort(unique(df$run))

# Calculate overlap
overlap_vdj <- calc_pairwise_overlaps(unique_peptides_vdj)
overlap_cdr3 <- calc_pairwise_overlaps(unique_peptides_cdr3)

jaccard_vdj_mtx <- overlap_vdj %>% select(name1, name2, jaccard) %>% acast(name1~name2, value.var = "jaccard")
jaccard_cdr3_mtx <- overlap_cdr3 %>% select(name1, name2, jaccard) %>% acast(name1~name2, value.var = "jaccard")

shared_vdj_mtx <- overlap_vdj %>% select(name1, name2, num_shared) %>% acast(name1~name2, value.var = "num_shared")
shared_cdr3_mtx <- overlap_cdr3 %>% select(name1, name2, num_shared) %>% acast(name1~name2, value.var = "num_shared")
```

```{r fig.height=4, fig.width=4}
pdf(file = "figures/jaccard_vdj_mtx_legend.pdf", width = 4, height = 4)

corrplot(jaccard_vdj_mtx, method = "color", col = COL1('YlOrRd', 200), col.lim = c(0,1),
         type = "lower", is.corr = F, diag = F,
         tl.srt = 0, tl.col = "black", tl.offset = 0.5, addCoef.col = "black", number.digits = 2)

dev.off()
```

```{r fig.height=4, fig.width=4}
pdf(file = "figures/jaccard_vdj_mtx.pdf", width = 4, height = 4)

corrplot(jaccard_vdj_mtx, method = "color", col = COL1('YlOrRd', 200), col.lim = c(0,1),
         type = "lower", is.corr = F, diag = F, cl.pos = "n",
         tl.srt = 0, tl.col = "black", tl.offset = 0.5, addCoef.col = "black", number.digits = 2)

dev.off()
```

```{r fig.height=4, fig.width=4}
pdf(file = "figures/jaccard_cdr3_mtx.pdf", width = 4, height = 4)

corrplot(jaccard_cdr3_mtx, method = "color", col = COL1('YlOrRd', 200), col.lim = c(0,1),
         type = "upper", is.corr = F, diag = F, cl.pos = "n",
         tl.srt = 0, tl.col = "black", tl.offset = 0.5, addCoef.col = "black", number.digits = 2)

dev.off()
```

```{r fig.height=4, fig.width=4}
pdf(file = "figures/shared_vdj_mtx_legend.pdf", width = 4, height = 4)

corrplot(shared_vdj_mtx, method = "color", col = COL1('YlOrRd', 400), col.lim = c(0,550),
         type = "lower", is.corr = F, diag = F, #cl.pos = "n",
         tl.srt = 0, tl.col = "black", tl.offset = 0.5, addCoef.col = "black", number.digits = 2)

dev.off()
```

```{r fig.height=4, fig.width=4}
pdf(file = "figures/shared_vdj_mtx.pdf", width = 4, height = 4)

corrplot(shared_vdj_mtx, method = "color", col = COL1('YlOrRd', 400), col.lim = c(0,550),
         type = "lower", is.corr = F, diag = F, cl.pos = "n",
         tl.srt = 0, tl.col = "black", tl.offset = 0.5, addCoef.col = "black", number.digits = 2)

dev.off()
```

```{r fig.height=4, fig.width=4}
pdf(file = "figures/shared_cdr3_mtx.pdf", width = 4, height = 4)

corrplot(shared_cdr3_mtx, method = "color", col = COL1('YlOrRd', 400), col.lim = c(0,550),
         type = "upper", is.corr = F, diag = F, cl.pos = "n",
         tl.srt = 0, tl.col = "black", tl.offset = 0.5, addCoef.col = "black", number.digits = 2)

dev.off()
```