---
title: "Suppfig_BSA_signal_intensity"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
source("../../Khang_config.R")
source("../../utils.R")
```

```{r Preprocessing, include=FALSE}
# Load the BSA + Hela data
df_60s <- read_tsv("./data/BSA_HeLa/peptides_EH1130-EH1141_BSA_HeLa_60s.txt")
df_100s <- read_tsv("./data/BSA_HeLa/peptides_EH1512-EH1523_BSA_HeLA_100s_fast.txt")

# Retain only serum albumin
df_60s <- df_60s[df_60s$`Leading razor protein` == "P02769", ]
df_100s <- df_100s[df_100s$`Leading razor protein` == "P02769", ]

# Remove contaminant peptides (CON in leading razor protein)
#df_60s <- df_60s %>% filter(!str_detect(`Leading razor protein`,"CON"))
#df_100s <- df_100s %>% filter(!str_detect(`Leading razor protein`,"CON"))

# Retain only relevant columns
df_60s <- df_60s[,c(1,74:85)]
df_100s <- df_100s[,c(1,74:85)]

# Transpose into long format, with each row having only 1 intensity
df_60s <- df_60s %>% pivot_longer(cols = `Intensity 500fmol BSA+HeLa_1`:`Intensity 5pmol BSA+HeLa_3`, names_to = "Sample", values_to = "Intensity")
df_100s <- df_100s %>% pivot_longer(cols = `Intensity 500fmol BSA+HeLa_1`:`Intensity 5pmol BSA+HeLa_3`, names_to = "Sample", values_to = "Intensity")

# Add column for input, sample number, method
df_60s$Input <- str_split(df_60s$Sample, " ", simplify = T)[, 2]
df_100s$Input <- str_split(df_100s$Sample, " ", simplify = T)[, 2]
df_60s$Input <- str_replace_all(df_60s$Input, "5pmol", "5000fmol")
df_100s$Input <- str_replace_all(df_100s$Input, "5pmol", "5000fmol")
df_60s$Input <- as.numeric(str_remove_all(df_60s$Input, "fmol"))
df_100s$Input <- as.numeric(str_remove_all(df_100s$Input, "fmol"))

df_60s$Sample <- str_split(df_60s$Sample, " ", simplify = T)[, 3]
df_100s$Sample <- str_split(df_100s$Sample, " ", simplify = T)[, 3]

# Remove all rows with Intensity 0
df_60s <- df_60s %>% filter(!Intensity == 0)
df_100s <- df_100s %>% filter(!Intensity == 0)

df_60s$Method <- "60"
df_100s$Method <- "100"
```

# Calculate the signal intensity ratios
```{r}
res_ratio_60s <- df_60s %>%
  left_join(df_60s, by = c("Sequence"), relationship = "many-to-many") %>% 
  filter(Sample.x != Sample.y | Input.x != Input.y) %>% 
  summarise(Sequence = Sequence,
            Sample1 = Sample.x,
            Sample2 = Sample.y,
            Intensity1 = Intensity.x, 
            Intensity2 = Intensity.y,
            Intensity_ratio = Intensity.x/Intensity.y,
            Input1 = Input.x,
            Input2 = Input.y,
            Input_ratio = Input.x/Input.y
            )

# Perform inversion in cases when sample x is lower input than sample y
idx <- res_ratio_60s$Input_ratio < 1
res_ratio_60s$Input_ratio[idx] <- 1/res_ratio_60s$Input_ratio[idx]
res_ratio_60s$Intensity_ratio[idx] <- 1/res_ratio_60s$Intensity_ratio[idx]
#res_ratio_60s$Input_ratio <- factor(res_ratio_60s$Input_ratio)

res_ratio_100s <- df_100s %>%
  left_join(df_100s, by = c("Sequence"), relationship = "many-to-many") %>% 
  filter(Sample.x != Sample.y | Input.x != Input.y) %>% 
  summarise(Sequence = Sequence,
            Sample1 = Sample.x,
            Sample2 = Sample.y,
            Intensity1 = Intensity.x, 
            Intensity2 = Intensity.y,
            Intensity_ratio = Intensity.x/Intensity.y,
            Input1 = Input.x,
            Input2 = Input.y,
            Input_ratio = Input.x/Input.y
            )

# Perform inversion in cases when sample x is lower input than sample y
idx <- res_ratio_100s$Input_ratio < 1
res_ratio_100s$Input_ratio[idx] <- 1/res_ratio_100s$Input_ratio[idx]
res_ratio_100s$Intensity_ratio[idx] <- 1/res_ratio_100s$Intensity_ratio[idx]
#res_ratio_100s$Input_ratio <- factor(res_ratio_100s$Input_ratio)
```

# Calculate the median, log10 transform, linear regression

```{r}
# Convert both intensity ratio and input ratio in log10 scale
res_ratio_60s$Log_intensity_ratio <- log10(res_ratio_60s$Intensity_ratio)
res_ratio_60s$Log_input_ratio <- log10(res_ratio_60s$Input_ratio)

res_ratio_100s$Log_intensity_ratio <- log10(res_ratio_100s$Intensity_ratio)
res_ratio_100s$Log_input_ratio <- log10(res_ratio_100s$Input_ratio)

# Calculate median of the log10 signal intensity ratio
res_ratio_60s_med <- res_ratio_60s %>% group_by(Input_ratio, Log_input_ratio) %>% summarise(Med = median(Log_intensity_ratio), Med2 = median(Intensity_ratio), N = n())

res_ratio_100s_med <- res_ratio_100s %>% group_by(Input_ratio, Log_input_ratio) %>% summarise(Med = median(Log_intensity_ratio), Med2 = median(Intensity_ratio), N = n())

# Make a linear regression model from the log sir, weighted by number of data points, extract the coefficients
lm_60s <- lm(Med~Log_input_ratio, weights = N, data = res_ratio_60s_med)
coefs_60s <- tibble(intercept = lm_60s$coefficients[1],
                    slope = lm_60s$coefficients[2],
                    r2 = summary(lm_60s)$r.squared)

coefs_60s$eq <- paste0("italic(log(y)) == ", format(coefs_60s$intercept, digits = 2, scientific = TRUE), 
                   " + ", format(coefs_60s$slope, digits = 2, scientific = TRUE), " %.% italic(log(x))")
coefs_60s$eq <- str_replace_all(coefs_60s$eq, "\\+ -", "\\- ")

coefs_60s$r2 <- paste0("italic(R)^2 == ", format(coefs_60s$r2, digits = 3))

lm_100s <- lm(Med~Log_input_ratio, weights = N, data = res_ratio_100s_med)
coefs_100s <- tibble(intercept = lm_100s$coefficients[1],
                    slope = lm_100s$coefficients[2],
                    r2 = summary(lm_100s)$r.squared)

coefs_100s$eq <- paste0("italic(log(y)) == ", format(coefs_100s$intercept, digits = 2, scientific = TRUE), 
                   " + ", format(coefs_100s$slope, digits = 2, scientific = TRUE), " %.% italic(log(x))")
coefs_100s$eq <- str_replace_all(coefs_100s$eq, "\\+ -", "\\- ")

coefs_100s$r2 <- paste0("italic(R)^2 == ", format(coefs_100s$r2, digits = 3))
```

# Plot the input vs intensity ratios as box + point plots
```{r fig.height=6, fig.width=6}
ggplot(res_ratio_60s, aes(x = Log_input_ratio, y = Log_intensity_ratio)) +
  geom_point(aes(fill = factor(Log_input_ratio)), color = "#FDBF6F", shape = 1, size = 1, stroke = 0.1, position = position_jitterdodge(jitter.width = 0.8)) +
  geom_boxplot(aes(fill = factor(Log_input_ratio)), width = 0.5, lwd = 0.5, outlier.shape = NA) +
  geom_abline(data = coefs_60s, aes(intercept = intercept, slope = slope), color = "#FF00F2", linewidth = 0.75, linetype = "dashed") +
  geom_abline(intercept = 0, slope = 1, color = "black", linewidth = 0.25) + # ground truth
  geom_text(data = res_ratio_60s_med, aes(x = Log_input_ratio, y = 4.2, label = round(Med2,1)), color = "black", size = 4) +
  geom_text(data = coefs_60s, aes(-0.75, -2.5, label = eq), parse = TRUE, size = 5, color = "black", hjust = 0) +
  geom_text(data = coefs_60s, aes(-0.75, -3, label = r2), parse = TRUE, size = 5, color = "black", hjust = 0) +
  scale_fill_manual(values = c("#FDBF6F", "#FDBF6F", "#FDBF6F", "#FDBF6F")) +
  scale_x_continuous(breaks = 0:3, labels = c(1, 10, 100, 1000)) +
  scale_y_continuous(breaks = -3:4, labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  theme_bw() +
  theme(legend.position = "none", text = element_text(size = 20), axis.text.x = element_text(angle = 0, vjust = 0.45)) +
  labs(x = "BSA input ratio", y = "MS signal intensity ratio")

#ggsave("./figures/bsa_intensity_60s.pdf", height = 6, width = 6, dpi = 600)
```

```{r fig.height=6, fig.width=6}
ggplot(res_ratio_100s, aes(x = Log_input_ratio, y = Log_intensity_ratio)) +
  geom_point(aes(fill = factor(Log_input_ratio)), color = "#FF7F00", shape = 1, size = 1, stroke = 0.1, position = position_jitterdodge(jitter.width = 0.8)) +
  geom_boxplot(aes(fill = factor(Log_input_ratio)), width = 0.5, lwd = 0.5, outlier.shape = NA) +
  geom_abline(data = coefs_100s, aes(intercept = intercept, slope = slope), color = "#FF00F2", linewidth = 0.75, linetype = "dashed") +
  geom_abline(intercept = 0, slope = 1, color = "black", linewidth = 0.25) + # ground truth
  geom_text(data = res_ratio_100s_med, aes(x = Log_input_ratio, y = 4.2, label = round(Med2,1)), color = "black", size = 4) +
  geom_text(data = coefs_100s, aes(-0.75, -2.5, label = eq), parse = TRUE, size = 5, color = "black", hjust = 0) +
  geom_text(data = coefs_100s, aes(-0.75, -3, label = r2), parse = TRUE, size = 5, color = "black", hjust = 0) +
  scale_fill_manual(values = c("#FF7F00", "#FF7F00", "#FF7F00", "#FF7F00")) +
  scale_x_continuous(breaks = 0:3, labels = c(1, 10, 100, 1000)) +
  scale_y_continuous(breaks = -3:4, labels = c(0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000)) +
  theme_bw() +
  theme(legend.position = "none", text = element_text(size = 20), axis.text.x = element_text(angle = 0, vjust = 0.45)) +
  labs(x = "BSA input ratio", y = "MS signal intensity ratio")

#ggsave("./figures/bsa_intensity_100s.pdf", height = 6, width = 6, dpi = 600)
```

```{r fig.height=6, fig.width=6}
ggplot(res_ratio_100s, aes(x = factor(Input_ratio), y = Intensity_ratio)) +
  geom_point(aes(color = Input_ratio), shape = 1, size = 1, stroke = 0.1, position = position_jitterdodge(jitter.width = 0.8)) +
  scale_color_manual(values = c("#FF7F00", "#FF7F00", "#FF7F00", "#FF7F00")) +
  geom_boxplot(fill = "#FF7F00", width = 0.5, lwd = 0.5, outlier.shape = NA) +
  scale_y_log10(breaks = 10^(-1:4), labels = c(0.1, 1, 10, 100, 1000, 10000)) +
  geom_text(data = median_100s, aes(x = Input_ratio, y = 0.1, label = round(median,2))) +
  geom_hline(yintercept=1, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=10, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=100, linetype="dotted", color = "#909090") +
  geom_hline(yintercept=1000, linetype="dotted", color = "#909090") +
  theme_classic() +
  theme(legend.position = "none", text = element_text(size = 20)) +
  labs(x = "BSA input ratio", y = "MS signal intensity ratio")

#ggsave("./figures/bsa_intensity_100s.pdf", height = 6, width = 6, dpi = 600)
```
